#!/usr/bin/env python3

# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the GiljoAI Community License v1.1.
# See LICENSE in the project root for terms.
# [CE] Community Edition — source-available, single-user use only.

"""
Reset Script for GiljoAI MCP Test Environment
Simulates a fresh installation while preserving critical files and symlinks.

This script:
1. Preserves CLAUDE.md, .serena/, and symlinked folders (docs, scripts, examples)
2. Copies fresh code from dev repo (C:/Projects/GiljoAI_MCP)
3. Drops PostgreSQL databases
4. Cleans %APPDATA% installations
5. Removes venv, .env, config.yaml, and other installation artifacts

NOTE: This script does NOT install anything. After running, you must manually run:
  - install.bat (Windows)
  - install.sh (Linux/Mac)
"""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


# Directories
TEST_DIR = Path(__file__).parent.resolve()
DEV_REPO = Path("C:/Projects/GiljoAI_MCP")

# PostgreSQL connection details
POSTGRES_PASSWORD = "4010"
PSQL_PATH = Path("C:/Program Files/PostgreSQL/18/bin/psql.exe")

# Files to preserve (CLAUDE.md and .gitignore only - installer recreates .env and config.yaml)
PRESERVE_FILES = {
    "CLAUDE.md",
    ".clauderc",
    ".gitignore",
    "reset.py",  # This script itself
}

# Folders to preserve (these are symlinks or critical config)
PRESERVE_FOLDERS = {
    ".serena",
    "docs",
    "scripts",
    "examples",
    "devlog",
}

# Files/folders that are environment-specific (never copy from dev repo)
# Note: .env and config.yaml will be regenerated by installer
ENVIRONMENT_SPECIFIC = {
    ".env",
    "config.yaml",
    "data",
    "logs",
    "uploads",
    "temp",
    "venv",
    "node_modules",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "api_keys.json",
    "install_logs",
    ".git",
    ".vscode",
    ".idea",
}


def print_header(text):
    """Print formatted header"""
    print("\n" + "=" * 70)
    print(f"  {text}")
    print("=" * 70 + "\n")


def confirm_action(message):
    """Ask user for confirmation"""
    response = input(f"\n{message} (y/N): ").strip().lower()
    return response == "y"


def is_symlink(path):
    """Check if path is a symlink (works on Windows)"""
    return path.is_symlink() or (path.exists() and path.is_dir() and os.path.islink(str(path)))


def drop_postgresql_databases():
    """Drop PostgreSQL databases"""
    print_header("Dropping PostgreSQL Databases")

    if not PSQL_PATH.exists():
        print(f"[!] PostgreSQL not found at {PSQL_PATH}")
        return False

    databases = ["giljo_mcp", "giljo_mcp_test"]

    for db in databases:
        print(f"Dropping database: {db}...")
        try:
            cmd = [str(PSQL_PATH), "-U", "postgres", "-c", f"DROP DATABASE IF EXISTS {db};"]
            env = os.environ.copy()
            env["PGPASSWORD"] = POSTGRES_PASSWORD

            result = subprocess.run(cmd, check=False, env=env, capture_output=True, text=True)

            if result.returncode == 0:
                print(f"[OK] Dropped database: {db}")
            else:
                print(f"[X] Failed to drop {db}: {result.stderr}")
        except Exception as e:
            print(f"[X] Error dropping {db}: {e}")

    # Also drop users
    users = ["giljo_user", "giljo_owner"]
    for user in users:
        print(f"Dropping user: {user}...")
        try:
            cmd = [str(PSQL_PATH), "-U", "postgres", "-c", f"DROP USER IF EXISTS {user};"]
            env = os.environ.copy()
            env["PGPASSWORD"] = POSTGRES_PASSWORD

            result = subprocess.run(cmd, check=False, env=env, capture_output=True, text=True)

            if result.returncode == 0:
                print(f"[OK] Dropped user: {user}")
        except Exception as e:
            print(f"[X] Error dropping {user}: {e}")

    return True


def clean_appdata():
    """Clean GiljoAI installations in %APPDATA%"""
    print_header("Cleaning AppData Installations")

    appdata = Path(os.environ.get("APPDATA", ""))
    if not appdata.exists():
        print("[!] APPDATA not found")
        return

    giljo_dirs = [
        appdata / "GiljoAI",
        appdata / "giljo_mcp",
    ]

    for dir_path in giljo_dirs:
        if dir_path.exists():
            print(f"Removing: {dir_path}")
            try:
                shutil.rmtree(dir_path)
                print(f"[OK] Removed: {dir_path}")
            except Exception as e:
                print(f"[X] Failed to remove {dir_path}: {e}")
        else:
            print(f"- Not found: {dir_path}")


def backup_preserved_items():
    """Backup files and folders that should be preserved"""
    print_header("Backing Up Preserved Items")

    backup_dir = TEST_DIR / ".reset_backup"
    backup_dir.mkdir(exist_ok=True)

    preserved = {}

    # Backup files
    for filename in PRESERVE_FILES:
        file_path = TEST_DIR / filename
        if file_path.exists():
            backup_path = backup_dir / filename
            print(f"Backing up: {filename}")
            shutil.copy2(file_path, backup_path)
            preserved[filename] = "file"

    # Backup folders (only if not symlinks)
    for foldername in PRESERVE_FOLDERS:
        folder_path = TEST_DIR / foldername
        if folder_path.exists():
            if is_symlink(folder_path):
                print(f"Preserving symlink: {foldername} -> {os.readlink(folder_path)}")
                preserved[foldername] = f"symlink:{os.readlink(folder_path)}"
            else:
                backup_path = backup_dir / foldername
                print(f"Backing up folder: {foldername}")
                if backup_path.exists():
                    shutil.rmtree(backup_path)
                shutil.copytree(folder_path, backup_path, symlinks=True)
                preserved[foldername] = "folder"

    # Save manifest
    manifest_path = backup_dir / "manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(preserved, f, indent=2)

    print(f"\n[OK] Backed up {len(preserved)} items to: {backup_dir}")
    return backup_dir


def clean_test_directory():
    """Remove all files except preserved items"""
    print_header("Cleaning Test Directory")

    # Items to keep during cleanup
    keep_items = {".reset_backup"} | PRESERVE_FOLDERS | PRESERVE_FILES

    removed_count = 0

    for item in TEST_DIR.iterdir():
        if item.name in keep_items:
            print(f"- Keeping: {item.name}")
            continue

        print(f"Removing: {item.name}")
        try:
            if item.is_dir():
                if is_symlink(item):
                    item.unlink()
                else:
                    shutil.rmtree(item)
            else:
                item.unlink()
            removed_count += 1
        except Exception as e:
            print(f"[X] Failed to remove {item.name}: {e}")

    print(f"\n[OK] Removed {removed_count} items")


def copy_from_dev_repo():
    """Copy fresh code from dev repository"""
    print_header("Copying Fresh Code from Dev Repo")

    if not DEV_REPO.exists():
        print(f"[X] Dev repo not found: {DEV_REPO}")
        return False

    # Directories to copy
    dirs_to_copy = [
        "api",
        "src",
        "frontend",
        "installer",
        "tests",
        "migrations",
        "docker",
        "launchers",
        "certs",
    ]

    # Root files to copy (code and configs, but not environment-specific)
    root_files = [
        # Python files
        # Note: setup_*.py files removed - use installer/cli/install.py instead
        "bootstrap.py",
        "start_giljo.py",
        "uninstall.py",
        "push_to_dev.py",
        "break_symlinks.py",
        # Note: Many utility scripts moved to /scripts directory
        # Batch files
        "start_giljo.bat",
        "start_backend.bat",
        "start_frontend.bat",
        "stop_giljo.bat",
        "stop_backend.bat",
        "stop_frontend.bat",
        "connect_project.bat",
        "setup_cli.bat",
        "setup_gui.bat",
        "register_claude.bat",
        "check_databases.bat",
        "install.bat",
        "open_dashboard.bat",
        # Shell scripts
        "start_giljo.sh",
        "stop_giljo.sh",
        "quickstart.sh",
        # Config files
        "requirements.txt",
        "pyproject.toml",
        "alembic.ini",
        "docker-compose.yml",
        "docker-compose.dev.yml",
        "docker-compose.prod.yml",
        "install_config.yaml",
        "config.yaml.example",
        "vite.config.js",
        "uv.lock",
        # Documentation
        "README.md",
        "LICENSE",
        "INSTALL.md",
        "QUICK_START.md",
        "SERVER_MODE_QUICKSTART.md",
        "INSTALLATION.md",
        "INSTALLER_ARCHITECTURE.md",
        "MIGRATION_NOTES.md",
        "SECURITY.md",
        "CONTRIBUTING.md",
        # Other
        ".release-ignore",
        ".clauderc",
        "giljo.ico",
        "favicon.jpg",
        "favicon.gif",
    ]

    copied_count = 0

    # Copy directories
    for dirname in dirs_to_copy:
        src_dir = DEV_REPO / dirname
        dst_dir = TEST_DIR / dirname

        if not src_dir.exists():
            print(f"[!] Source not found: {dirname}")
            continue

        print(f"Copying directory: {dirname}...")
        try:
            if dst_dir.exists():
                if is_symlink(dst_dir):
                    print(f"- Skipping symlink: {dirname}")
                    continue
                shutil.rmtree(dst_dir)

            shutil.copytree(
                src_dir,
                dst_dir,
                ignore=shutil.ignore_patterns(
                    "__pycache__", "*.pyc", ".pytest_cache", "node_modules", ".mypy_cache", ".ruff_cache"
                ),
            )
            copied_count += 1
            print(f"[OK] Copied: {dirname}")
        except Exception as e:
            print(f"[X] Failed to copy {dirname}: {e}")

    # Copy root files
    for filename in root_files:
        src_file = DEV_REPO / filename
        dst_file = TEST_DIR / filename

        if not src_file.exists():
            continue

        if filename in PRESERVE_FILES:
            print(f"- Skipping preserved file: {filename}")
            continue

        try:
            shutil.copy2(src_file, dst_file)
            copied_count += 1
        except Exception as e:
            print(f"[X] Failed to copy {filename}: {e}")

    print(f"\n[OK] Copied {copied_count} items from dev repo")
    return True


def restore_preserved_items(backup_dir):
    """Restore backed up files and folders"""
    print_header("Restoring Preserved Items")

    manifest_path = backup_dir / "manifest.json"
    if not manifest_path.exists():
        print("[X] No manifest found")
        return

    with open(manifest_path) as f:
        preserved = json.load(f)

    restored_count = 0

    for item_name, item_type in preserved.items():
        backup_path = backup_dir / item_name
        dest_path = TEST_DIR / item_name

        if item_type == "file":
            print(f"Restoring file: {item_name}")
            try:
                shutil.copy2(backup_path, dest_path)
                restored_count += 1
            except Exception as e:
                print(f"[X] Failed to restore {item_name}: {e}")

        elif item_type == "folder":
            print(f"Restoring folder: {item_name}")
            try:
                if dest_path.exists():
                    shutil.rmtree(dest_path)
                shutil.copytree(backup_path, dest_path, symlinks=True)
                restored_count += 1
            except Exception as e:
                print(f"[X] Failed to restore {item_name}: {e}")

        elif item_type.startswith("symlink:"):
            target = item_type.split(":", 1)[1]
            print(f"Preserving symlink: {item_name} -> {target}")
            # Symlink should still exist, just verify
            if dest_path.exists() and is_symlink(dest_path):
                print(f"[OK] Symlink preserved: {item_name}")
                restored_count += 1

    print(f"\n[OK] Restored {restored_count} items")

    # Clean up backup
    print("\nCleaning up backup directory...")
    try:
        shutil.rmtree(backup_dir)
        print("[OK] Backup removed")
    except Exception as e:
        print(f"[!] Could not remove backup: {e}")


def main():
    """Main reset process"""
    print_header("GiljoAI MCP Test Environment Reset")

    print(f"Test Directory: {TEST_DIR}")
    print(f"Dev Repository: {DEV_REPO}")
    print("\nThis will:")
    print("  - Drop PostgreSQL databases (giljo_mcp, giljo_mcp_test)")
    print("  - Drop PostgreSQL users (giljo_user, giljo_owner)")
    print("  - Clean %APPDATA% installations")
    print("  - Remove venv, .env, config.yaml (NOT reinstalled)")
    print("  - Copy fresh code from dev repo")
    print("  - Preserve CLAUDE.md, .serena/, and symlinked folders")
    print("\n[!] After reset, manually run:")
    print("      install.bat (Windows)")
    print("      quickstart.sh (Linux/Mac)")

    if not confirm_action("\nProceed with reset?"):
        print("\n[X] Reset cancelled")
        return 1

    # Step 1: Backup preserved items
    backup_dir = backup_preserved_items()

    # Step 2: Drop databases
    drop_postgresql_databases()

    # Step 3: Clean AppData
    clean_appdata()

    # Step 4: Clean test directory
    clean_test_directory()

    # Step 5: Copy from dev repo
    if not copy_from_dev_repo():
        print("\n[X] Failed to copy from dev repo")
        return 1

    # Step 6: Restore preserved items
    restore_preserved_items(backup_dir)

    print_header("Reset Complete!")
    print("\nYour test environment is ready for installation.")
    print("\nNext steps:")
    print("  1. Run installer:")
    print("       Windows: install.bat")
    print("       Linux/Mac: ./quickstart.sh")
    print("  2. Follow the installation prompts")
    print("  3. Test the installation")

    return 0


if __name__ == "__main__":
    sys.exit(main())
