"""add_target_platforms_to_products

Revision ID: aeef30e94762
Revises: 0390a_memory_entries
Create Date: 2026-01-19 22:31:13.675156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeef30e94762'
down_revision: Union[str, Sequence[str], None] = '0390a_memory_entries'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_session_project'), table_name='sessions')
    op.drop_index(op.f('idx_session_tenant'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('idx_augment_active'), table_name='template_augmentations')
    op.drop_index(op.f('idx_augment_template'), table_name='template_augmentations')
    op.drop_index(op.f('idx_augment_tenant'), table_name='template_augmentations')
    op.drop_table('template_augmentations')
    op.alter_column('agent_executions', 'agent_display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Human-readable display name for UI',
               existing_comment="UI display label assigned by orchestrator (e.g., 'Backend API Developer')",
               existing_nullable=False)
    op.alter_column('agent_executions', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='DEPRECATED: Use counter columns instead. Scheduled for removal in v4.0.',
               existing_comment='DEPRECATED (0387i): Use counter columns (messages_sent_count, messages_waiting_count, messages_read_count) instead. Scheduled for removal in v4.0.',
               existing_nullable=False)
    op.alter_column('agent_executions', 'messages_sent_count',
               existing_type=sa.INTEGER(),
               comment='Count of outbound messages sent by this agent',
               existing_comment='Count of outbound messages sent by this agent (Handover 0387e)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_executions', 'messages_waiting_count',
               existing_type=sa.INTEGER(),
               comment='Count of inbound messages waiting to be read',
               existing_comment='Count of inbound messages waiting to be read (Handover 0387e)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_executions', 'messages_read_count',
               existing_type=sa.INTEGER(),
               comment='Count of inbound messages that have been acknowledged/read',
               existing_comment='Count of inbound messages that have been acknowledged/read (Handover 0387e)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product_memory_entries', 'id',
               existing_type=sa.UUID(),
               comment='Unique entry identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('product_memory_entries', 'tenant_key',
               existing_type=sa.VARCHAR(length=36),
               comment='Tenant isolation key',
               existing_nullable=False)
    op.alter_column('product_memory_entries', 'product_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Parent product (CASCADE on delete)',
               existing_nullable=False)
    op.alter_column('product_memory_entries', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Source project (SET NULL on delete - preserves history)',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'sequence',
               existing_type=sa.INTEGER(),
               comment='Sequence number within product (1-based)',
               existing_nullable=False)
    op.alter_column('product_memory_entries', 'entry_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Entry type: project_closeout, project_completion, handover_closeout',
               existing_nullable=False)
    op.alter_column('product_memory_entries', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='Source tool: closeout_v1, write_360_memory_v1, migration_backfill',
               existing_nullable=False)
    op.alter_column('product_memory_entries', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the entry was created',
               existing_nullable=False)
    op.alter_column('product_memory_entries', 'project_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Project name at time of entry',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'summary',
               existing_type=sa.TEXT(),
               comment='2-3 paragraph summary of work accomplished',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'key_outcomes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of key achievements',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('product_memory_entries', 'decisions_made',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of architectural/design decisions',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('product_memory_entries', 'git_commits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of git commit objects with sha, message, author',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('product_memory_entries', 'deliverables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of files/artifacts delivered',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('product_memory_entries', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Metrics dict (test_coverage, etc.)',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('product_memory_entries', 'priority',
               existing_type=sa.INTEGER(),
               comment='Priority level 1-5',
               existing_nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('product_memory_entries', 'significance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Significance score 0.0-1.0',
               existing_nullable=True,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('product_memory_entries', 'token_estimate',
               existing_type=sa.INTEGER(),
               comment='Estimated tokens for this entry',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of tags for categorization',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('product_memory_entries', 'author_job_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Job ID of agent that wrote this entry',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'author_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of agent that wrote this entry',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'author_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of agent (orchestrator, implementer, etc.)',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'deleted_by_user',
               existing_type=sa.BOOLEAN(),
               comment='True if source project was deleted by user',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('product_memory_entries', 'user_deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the source project was deleted',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='When this row was created',
               existing_server_default=sa.text('now()'))
    op.alter_column('product_memory_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='When this row was last updated',
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_product_memory_entries_tenant_key'), 'product_memory_entries', ['tenant_key'], unique=False)
    op.add_column('products', sa.Column('target_platforms', sa.ARRAY(sa.String()), server_default=sa.text("'{all}'::text[]"), nullable=False, comment='Target platforms: windows, linux, macos, or all'))
    op.alter_column('products', 'product_memory',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Product memory storage. NOTE: 'sequential_history' field is DEPRECATED as of v3.3 (Handover 0390). Use product_memory_entries table instead. Only 'git_integration' config remains in use. WILL BE MODIFIED in v4.0 to remove sequential_history.",
               existing_comment='360 Memory: GitHub integration, sequential history, context summaries (Handover 0135)',
               existing_nullable=False,
               existing_server_default=sa.text('\'{"github": {}, "context": {}, "sequential_history": []}\'::jsonb'))
    op.create_foreign_key(None, 'tasks', 'agent_jobs', ['job_id'], ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('products', 'product_memory',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='360 Memory: GitHub integration, sequential history, context summaries (Handover 0135)',
               existing_comment="Product memory storage. NOTE: 'sequential_history' field is DEPRECATED as of v3.3 (Handover 0390). Use product_memory_entries table instead. Only 'git_integration' config remains in use. WILL BE MODIFIED in v4.0 to remove sequential_history.",
               existing_nullable=False,
               existing_server_default=sa.text('\'{"github": {}, "context": {}, "sequential_history": []}\'::jsonb'))
    op.drop_column('products', 'target_platforms')
    op.drop_index(op.f('ix_product_memory_entries_tenant_key'), table_name='product_memory_entries')
    op.alter_column('product_memory_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='When this row was last updated',
               existing_server_default=sa.text('now()'))
    op.alter_column('product_memory_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='When this row was created',
               existing_server_default=sa.text('now()'))
    op.alter_column('product_memory_entries', 'user_deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the source project was deleted',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'deleted_by_user',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True if source project was deleted by user',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('product_memory_entries', 'author_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type of agent (orchestrator, implementer, etc.)',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'author_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Name of agent that wrote this entry',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'author_job_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Job ID of agent that wrote this entry',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of tags for categorization',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('product_memory_entries', 'token_estimate',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Estimated tokens for this entry',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'significance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Significance score 0.0-1.0',
               existing_nullable=True,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('product_memory_entries', 'priority',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Priority level 1-5',
               existing_nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('product_memory_entries', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Metrics dict (test_coverage, etc.)',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('product_memory_entries', 'deliverables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of files/artifacts delivered',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('product_memory_entries', 'git_commits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of git commit objects with sha, message, author',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('product_memory_entries', 'decisions_made',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of architectural/design decisions',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('product_memory_entries', 'key_outcomes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of key achievements',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('product_memory_entries', 'summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='2-3 paragraph summary of work accomplished',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'project_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Project name at time of entry',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the entry was created',
               existing_nullable=False)
    op.alter_column('product_memory_entries', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Source tool: closeout_v1, write_360_memory_v1, migration_backfill',
               existing_nullable=False)
    op.alter_column('product_memory_entries', 'entry_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Entry type: project_closeout, project_completion, handover_closeout',
               existing_nullable=False)
    op.alter_column('product_memory_entries', 'sequence',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Sequence number within product (1-based)',
               existing_nullable=False)
    op.alter_column('product_memory_entries', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Source project (SET NULL on delete - preserves history)',
               existing_nullable=True)
    op.alter_column('product_memory_entries', 'product_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Parent product (CASCADE on delete)',
               existing_nullable=False)
    op.alter_column('product_memory_entries', 'tenant_key',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Tenant isolation key',
               existing_nullable=False)
    op.alter_column('product_memory_entries', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique entry identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('agent_executions', 'messages_read_count',
               existing_type=sa.INTEGER(),
               comment='Count of inbound messages that have been acknowledged/read (Handover 0387e)',
               existing_comment='Count of inbound messages that have been acknowledged/read',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_executions', 'messages_waiting_count',
               existing_type=sa.INTEGER(),
               comment='Count of inbound messages waiting to be read (Handover 0387e)',
               existing_comment='Count of inbound messages waiting to be read',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_executions', 'messages_sent_count',
               existing_type=sa.INTEGER(),
               comment='Count of outbound messages sent by this agent (Handover 0387e)',
               existing_comment='Count of outbound messages sent by this agent',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_executions', 'messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='DEPRECATED (0387i): Use counter columns (messages_sent_count, messages_waiting_count, messages_read_count) instead. Scheduled for removal in v4.0.',
               existing_comment='DEPRECATED: Use counter columns instead. Scheduled for removal in v4.0.',
               existing_nullable=False)
    op.alter_column('agent_executions', 'agent_display_name',
               existing_type=sa.VARCHAR(length=100),
               comment="UI display label assigned by orchestrator (e.g., 'Backend API Developer')",
               existing_comment='Human-readable display name for UI',
               existing_nullable=False)
    op.create_table('template_augmentations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_key', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('augmentation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_section', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['agent_templates.id'], name=op.f('template_augmentations_template_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('template_augmentations_pkey'))
    )
    op.create_index(op.f('idx_augment_tenant'), 'template_augmentations', ['tenant_key'], unique=False)
    op.create_index(op.f('idx_augment_template'), 'template_augmentations', ['template_id'], unique=False)
    op.create_index(op.f('idx_augment_active'), 'template_augmentations', ['is_active'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_key', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('session_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('objectives', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcomes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('decisions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('blockers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('next_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('sessions_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey')),
    sa.UniqueConstraint('project_id', 'session_number', name=op.f('uq_session_project_number'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_session_tenant'), 'sessions', ['tenant_key'], unique=False)
    op.create_index(op.f('idx_session_project'), 'sessions', ['project_id'], unique=False)
    # ### end Alembic commands ###
