# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the GiljoAI Community License v1.1.
# See LICENSE in the project root for terms.
# [CE] Community Edition — source-available, single-user use only.

"""
Service-layer Pydantic response models.

These models provide typed return values for service methods,
replacing dict[str, Any] returns with validated, documented models.

Created: Handover 0731
"""

from src.giljo_mcp.schemas.service_responses import (
    ApiKeyCreateResult,
    ApiKeyInfo,
    AuthResult,
    BroadcastResult,
    CascadeImpact,
    CompleteJobResult,
    ConsolidationResult,
    ConversionResult,
    DeleteResult,
    ErrorReportResult,
    GitIntegrationSettings,
    InstructionsResponse,
    JobListResult,
    MessageListResult,
    MissionResponse,
    MissionUpdateResult,
    OperationResult,
    PaginatedResult,
    PathValidationResult,
    PendingJobsResult,
    ProductStatistics,
    ProgressResult,
    PurgeResult,
    SendMessageResult,
    SetupState,
    SetupStateInfo,
    SpawnResult,
    SuccessionContextResult,
    SuccessionResult,
    SuccessionStatus,
    TaskListResponse,
    TaskSummary,
    TaskUpdateResult,
    TemplateListResult,
    TransferResult,
    UserInfo,
    VisionUploadResult,
    WorkflowStatus,
)

__all__ = [
    "ApiKeyCreateResult",
    "ApiKeyInfo",
    "AuthResult",
    "BroadcastResult",
    "CascadeImpact",
    "CompleteJobResult",
    "ConsolidationResult",
    "ConversionResult",
    "DeleteResult",
    "ErrorReportResult",
    "GitIntegrationSettings",
    "InstructionsResponse",
    "JobListResult",
    "MessageListResult",
    "MissionResponse",
    "MissionUpdateResult",
    "OperationResult",
    "PaginatedResult",
    "PathValidationResult",
    "PendingJobsResult",
    "ProductStatistics",
    "ProgressResult",
    "PurgeResult",
    "SendMessageResult",
    "SetupState",
    "SetupStateInfo",
    "SpawnResult",
    "SuccessionContextResult",
    "SuccessionResult",
    "SuccessionStatus",
    "TaskListResponse",
    "TaskSummary",
    "TaskUpdateResult",
    "TemplateListResult",
    "TransferResult",
    "UserInfo",
    "VisionUploadResult",
    "WorkflowStatus",
]
