"""Developer Panel backend endpoints (Phase 1003).

All routes are guarded by:
- Environment flag ENABLE_DEVPANEL=true
- Localhost request (127.0.0.1 or ::1)

Data sources come from JSON inventories generated by scripts/devpanel_index.py.
"""

from __future__ import annotations

import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict

from fastapi import APIRouter, Depends, HTTPException, Request


router = APIRouter(prefix="/api/v1/developer", tags=["developer-panel"])


def _env_flag_enabled() -> bool:
    return os.getenv("ENABLE_DEVPANEL", "false").lower() == "true"


def _default_index_dir() -> Path:
    candidate = os.getenv("DEVPANEL_INDEX_DIR")
    if candidate:
        return Path(candidate).expanduser().resolve()
    return (Path.cwd() / "temp" / "devpanel" / "index").resolve()


INDEX_DIR = _default_index_dir()


def require_devpanel_access(request: Request) -> None:
    if not _env_flag_enabled():
        raise HTTPException(status_code=404, detail="Not Found")

    client = request.client
    client_host = client.host if client else None
    if client_host not in {"127.0.0.1", "::1", "testclient"}:
        raise HTTPException(status_code=403, detail="Developer panel available from localhost only")


@lru_cache(maxsize=64)
def _load_json_cached(filename: str, mtime: float) -> Dict[str, Any]:
    path = INDEX_DIR / filename
    try:
        with path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError as exc:
        raise HTTPException(status_code=404, detail=f"Inventory '{filename}' not found") from exc
    except json.JSONDecodeError as exc:
        raise HTTPException(status_code=500, detail=f"Inventory '{filename}' is not valid JSON") from exc


def load_inventory(filename: str) -> Dict[str, Any]:
    path = INDEX_DIR / filename
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Inventory '{filename}' not found")
    stat = path.stat()
    return _load_json_cached(filename, stat.st_mtime)


def developer_router_dependency(request: Request) -> None:
    require_devpanel_access(request)


@router.get("/health", dependencies=[Depends(developer_router_dependency)])
async def developer_health() -> Dict[str, Any]:
    return {
        "status": "enabled",
        "index_dir": str(INDEX_DIR),
        "inventories": {
            "api_catalog": (INDEX_DIR / "api_catalog.json").exists(),
            "mcp_tool_catalog": (INDEX_DIR / "mcp_tool_catalog.json").exists(),
            "db_schema": (INDEX_DIR / "db_schema.json").exists(),
            "dependency_index": (INDEX_DIR / "dependency_index.json").exists(),
            "flows_index": (INDEX_DIR / "flows_index.json").exists(),
            "search_index_seed": (INDEX_DIR / "search_index_seed.json").exists(),
        },
    }


@router.get("/api-catalog", dependencies=[Depends(developer_router_dependency)])
async def get_api_catalog() -> Dict[str, Any]:
    return load_inventory("api_catalog.json")


@router.get("/mcp-tools", dependencies=[Depends(developer_router_dependency)])
async def get_mcp_tool_catalog() -> Dict[str, Any]:
    return load_inventory("mcp_tool_catalog.json")


@router.get("/agents-templates", dependencies=[Depends(developer_router_dependency)])
async def get_agents_templates() -> Dict[str, Any]:
    # To be populated by future phases (agent template catalog)
    return load_inventory("agent_template_catalog.json")


@router.get("/db-schema", dependencies=[Depends(developer_router_dependency)])
async def get_db_schema() -> Dict[str, Any]:
    return load_inventory("db_schema.json")


@router.get("/dependency-index", dependencies=[Depends(developer_router_dependency)])
async def get_dependency_index() -> Dict[str, Any]:
    return load_inventory("dependency_index.json")


@router.get("/flows", dependencies=[Depends(developer_router_dependency)])
async def get_flows() -> Dict[str, Any]:
    return load_inventory("flows_index.json")


@router.get("/search-index", dependencies=[Depends(developer_router_dependency)])
async def get_search_index() -> Dict[str, Any]:
    return load_inventory("search_index_seed.json")


@router.get("/tech-stack", dependencies=[Depends(developer_router_dependency)])
async def get_tech_stack() -> Dict[str, Any]:
    return load_inventory("tech_stack.json")
