# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the Elastic License 2.0.
# See LICENSE in the project root for terms.
# [CE] Community Edition.

"""Tenant data portability endpoints (BE-5062, GDPR "Export My Data").

Available in CE and SaaS.

Gate:
    GILJO_MODE == 'saas' AND current_user.role != 'admin' -> 403
    otherwise (CE single-user, or SaaS org admin)         -> 200

Tenant isolation is enforced one layer deeper, in TenantExportService — every
SQL query filters WHERE tenant_key == current_user.tenant_key, so a SaaS org
admin can only export rows belonging to THEIR org.

POST /api/v1/account/export
    Returns {"download_url", "expires_at", "model_counts"} on success.
    Reuses the existing DownloadToken + /api/download/temp/{token}/{filename}
    pipeline; the staged ZIP is generated by TenantExportService.
"""

from __future__ import annotations

import logging
import shutil

from fastapi import APIRouter, Depends, HTTPException, Request, status
from sqlalchemy.ext.asyncio import AsyncSession

from giljo_mcp.auth.dependencies import get_current_active_user, get_db_session
from giljo_mcp.http.url_resolver import get_public_base_url
from giljo_mcp.models import User
from giljo_mcp.services.tenant_export_service import TenantExportService
from giljo_mcp.utils.log_sanitizer import mask_token, sanitize


logger = logging.getLogger(__name__)
router = APIRouter(tags=["tenant-data"])


_EXPORT_FILENAME = "tenant_export.zip"


@router.post("/export", status_code=status.HTTP_200_OK)
async def export_tenant_data(
    request: Request,
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db_session),
) -> dict:
    """Export the authenticated user's tenant data as a downloadable ZIP.

    Returns a one-time download URL (15-minute TTL) plus per-model row counts.
    """
    # Mode gate must be evaluated at request time so tests can patch
    # ``api.app_state.GILJO_MODE`` without re-importing this module.
    from api.app_state import GILJO_MODE

    # SaaS requires admin role to export org-level data. CE keeps the original
    # "any authenticated user" rule because single-user CE installs treat the
    # operator as the de-facto admin (gating to role==admin there adds friction
    # with no security gain). Tenant isolation in TenantExportService stops a
    # SaaS admin from ever reaching another org's data.
    if GILJO_MODE == "saas" and current_user.role != "admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Data export requires an organization admin role.",
        )

    tenant_key = current_user.tenant_key
    ws_manager = getattr(request.app.state, "websocket_manager", None)

    logger.info(
        "Starting tenant export for user=%s tenant=%s",
        sanitize(current_user.username),
        sanitize(tenant_key),
    )

    service = TenantExportService(db_session=db, websocket_manager=ws_manager)
    zip_path, model_counts = await service.export(tenant_key=tenant_key)

    # Stage the ZIP into temp/{tenant_key}/{token}/ and create a DownloadToken
    # via the existing pipeline. The CHECK constraint on
    # download_tokens.download_type was extended in migration ce_0025 to
    # include 'tenant_export' alongside the original two values.
    from giljo_mcp.downloads.token_manager import TokenManager
    from giljo_mcp.file_staging import FileStaging

    token_manager = TokenManager(db_session=db)
    token = await token_manager.generate_token(
        tenant_key=tenant_key,
        download_type="tenant_export",
        filename=_EXPORT_FILENAME,
    )

    staging = FileStaging(db_session=db)
    staging_dir = await staging.create_staging_directory(tenant_key, token)
    staged_path = staging_dir / _EXPORT_FILENAME
    shutil.move(str(zip_path), str(staged_path))

    await token_manager.mark_ready(token)

    server_url = get_public_base_url(request)
    download_url = f"{server_url}/api/download/temp/{token}/{_EXPORT_FILENAME}"

    token_data = await token_manager.get_token_info(token, tenant_key)
    expires_at = token_data["expires_at"] if token_data else None

    logger.info(
        "Tenant export ready: tenant=%s token=%s bytes=%d models=%d",
        sanitize(tenant_key),
        mask_token(token),
        staged_path.stat().st_size,
        len(model_counts),
    )

    return {
        "download_url": download_url,
        "expires_at": expires_at,
        "model_counts": model_counts,
    }
