#!/usr/bin/env python3
"""
Dev Panel Installer (optional add-on)

Sets up an isolated Developer Panel database and read-only access to the main DB.
Writes a local `.env.devpanel` with gating flags so any experimental services under
`dev_tools/devpanel` can mount /developer-style routes without touching the main app.

This script lives outside the production codebase and performs no writes to
application tables.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from textwrap import dedent


REPO_ROOT = Path(__file__).resolve().parents[3]


def write_env_file(path: Path, panel_db_url: str, source_ro_url: str | None) -> None:
    content = [
        "# Generated by dev_tools/devpanel/scripts/devpanel_install.py",
        "ENABLE_DEVPANEL=true",
        "ALLOW_DEVPANEL_EDIT=false",
        f"DEVPANEL_DATABASE_URL={panel_db_url}",
    ]
    if source_ro_url:
        content.append(f"DEVPANEL_READONLY_DB_URL={source_ro_url}")
    path.write_text("\n".join(content) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Install Developer Panel tooling (isolated from main app)")
    parser.add_argument(
        "--panel-db-url", default="sqlite:///devpanel.db", help="Database URL for Dev Panel data (default: sqlite)"
    )
    parser.add_argument("--source-db-url", default=os.getenv("DATABASE_URL"), help="Main DB URL for read-only access")
    parser.add_argument("--create-ro-user", action="store_true", help="Print SQL to create a read-only PostgreSQL user")
    parser.add_argument("--ro-username", default="devpanel_ro", help="RO username to create/use")
    parser.add_argument("--ro-password", default=None, help="RO password to create/use")
    parser.add_argument("--env-out", default=".env.devpanel", help="Path to write devpanel env flags")
    parser.add_argument("--dry-run", action="store_true", help="Plan only, do not apply")
    args = parser.parse_args()

    print("== GiljoAI MCP – Dev Panel Installer ==")
    print(f"Panel DB URL:   {args.panel_db_url}")
    print(f"Source DB URL:  {args.source_db_url or '(none)'}")

    # Ensure sqlite file exists when required
    if args.panel_db_url.startswith("sqlite:///"):
        db_file = args.panel_db_url.replace("sqlite:///", "")
        Path(db_file).touch()
        print(f"Created/verified SQLite file: {db_file}")

    ro_url = None
    if args.create_ro_user:
        if not args.source_db_url or not args.source_db_url.startswith("postgresql"):
            print("[WARN] --create-ro-user requires a PostgreSQL admin connection in --source-db-url")
        else:
            if not args.ro_password:
                print("[WARN] No --ro-password provided; supplying template password CHANGEME")
            print("\nSQL to run on PostgreSQL (manual, for safety):\n")
            print(
                dedent(f"""
                -- Create RO role for Dev Panel (adjust schema name as needed)
                CREATE ROLE {args.ro_username} LOGIN PASSWORD '{args.ro_password or "CHANGEME"}';
                GRANT CONNECT ON DATABASE current_database() TO {args.ro_username};
                GRANT USAGE ON SCHEMA public TO {args.ro_username};
                GRANT SELECT ON ALL TABLES IN SCHEMA public TO {args.ro_username};
                ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO {args.ro_username};
            """)
            )
            print("\nApply the SQL using an admin account, then set DEVPANEL_READONLY_DB_URL accordingly.\n")

            if args.ro_password:
                ro_url = f"postgresql+psycopg://{args.ro_username}:{args.ro_password}@HOST:5432/DBNAME"
                print(f"Template RO URL: {ro_url}")

    env_path = Path(args.env_out)
    if args.dry_run:
        print(f"[DRY RUN] Would write env to {env_path}")
    else:
        write_env_file(env_path, args.panel_db_url, ro_url)
        print(f"Wrote {env_path}")

    print("\nNext steps:")
    print("1) source .env.devpanel")
    print("2) Run dev_tools/devpanel/scripts/devpanel_index.py to build inventories")
    print("3) Start any experimental panel services under dev_tools/devpanel")
    print("\nUninstall: delete .env.devpanel and the panel DB file (e.g., devpanel.db)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
