"""Add activated_at and paused_at fields to projects

Revision ID: 4efd65f41897
Revises: 46a46cb1310b
Create Date: 2025-11-13 00:33:50.593833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4efd65f41897'
down_revision: Union[str, Sequence[str], None] = '46a46cb1310b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents_backup_final')
    op.drop_index(op.f('idx_agent_project'), table_name='agents')
    op.drop_index(op.f('idx_agent_status'), table_name='agents')
    op.drop_index(op.f('idx_agent_tenant'), table_name='agents')
    op.drop_index(op.f('ix_agents_job_id'), table_name='agents')
    op.drop_table('agents')
    op.alter_column('mcp_agent_jobs', 'failure_reason',
               existing_type=sa.VARCHAR(length=50),
               comment='Reason for failure: error, timeout, system_error (Handover 0113)',
               existing_comment='Reason for failure: error, timeout, system_error',
               existing_nullable=True)
    op.alter_column('mcp_agent_jobs', 'last_message_check_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last message queue check (Handover 0107)',
               existing_comment='Timestamp of last message queue check by agent (Handover 0107)',
               existing_nullable=True)
    op.add_column('projects', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True, comment='First activation timestamp (only set once on first activation)'))
    op.add_column('projects', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when project was last paused/deactivated'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'paused_at')
    op.drop_column('projects', 'activated_at')
    op.alter_column('mcp_agent_jobs', 'last_message_check_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of last message queue check by agent (Handover 0107)',
               existing_comment='Timestamp of last message queue check (Handover 0107)',
               existing_nullable=True)
    op.alter_column('mcp_agent_jobs', 'failure_reason',
               existing_type=sa.VARCHAR(length=50),
               comment='Reason for failure: error, timeout, system_error',
               existing_comment='Reason for failure: error, timeout, system_error (Handover 0113)',
               existing_nullable=True)
    op.create_table('agents',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_key', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mission', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('context_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_active', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('decommissioned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(length=20), server_default=sa.text("'claude'::character varying"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('agents_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agents_pkey')),
    sa.UniqueConstraint('project_id', 'name', name=op.f('uq_agent_project_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_agents_job_id'), 'agents', ['job_id'], unique=False)
    op.create_index(op.f('idx_agent_tenant'), 'agents', ['tenant_key'], unique=False)
    op.create_index(op.f('idx_agent_status'), 'agents', ['status'], unique=False)
    op.create_index(op.f('idx_agent_project'), 'agents', ['project_id'], unique=False)
    op.create_table('agents_backup_final',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('tenant_key', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mission', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('context_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_active', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('decommissioned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    comment='Backup of agents table before Handover 0116 drop. Created 2025-11-07. Safe to drop after 2025-12-07 (30 days).'
    )
    # ### end Alembic commands ###
