"""Add ApiMetrics table

Revision ID: 9fdd0e67585f
Revises: 20251106_0108
Create Date: 2025-11-06 21:32:37.109546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fdd0e67585f'
down_revision: Union[str, Sequence[str], None] = '20251106_0108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_api_calls', sa.Integer(), nullable=True),
    sa.Column('total_mcp_calls', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_metrics_tenant_date', 'api_metrics', ['tenant_key', 'date'], unique=False)
    op.create_index(op.f('ix_api_metrics_tenant_key'), 'api_metrics', ['tenant_key'], unique=True)
    op.alter_column('agent_templates', 'system_instructions',
               existing_type=sa.TEXT(),
               comment='Protected MCP coordination instructions (non-editable by users)',
               existing_comment='Protected MCP coordination rules (non-editable by users)',
               existing_nullable=False)
    op.alter_column('agent_templates', 'template_content',
               existing_type=sa.TEXT(),
               comment='DEPRECATED (v3.1): Use system_instructions + user_instructions. Kept for backward compatibility.',
               existing_comment='DEPRECATED (v3.1): Use system_instructions + user_instructions instead. Will be removed in v4.0.',
               existing_nullable=False)
    op.alter_column('agent_templates', 'cli_tool',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('idx_agent_templates_system_instructions_gin'), table_name='agent_templates', postgresql_ops={'system_instructions': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('download_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               comment='Deprecated: legacy one-time download flag (not enforced)',
               existing_comment='Tracks if token has been used (one-time download)',
               existing_nullable=False)
    op.alter_column('download_tokens', 'downloaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Deprecated: legacy single-use timestamp (not enforced)',
               existing_comment='Timestamp when download occurred',
               existing_nullable=True)
    op.drop_index(op.f('idx_download_tokens_status'), table_name='download_tokens')
    op.alter_column('mcp_agent_jobs', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Project ID this job belongs to (Handover 0062)',
               existing_nullable=True)
    op.alter_column('mcp_agent_jobs', 'job_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSONB metadata for thin client architecture (Handover 0088). Stores field_priorities, user_id, tool, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_mcp_agent_jobs_health_status'), table_name='mcp_agent_jobs')
    op.drop_index(op.f('idx_mcp_agent_jobs_job_metadata'), table_name='mcp_agent_jobs', postgresql_using='gin')
    op.create_index(op.f('ix_mcp_agent_jobs_project_id'), 'mcp_agent_jobs', ['project_id'], unique=False)
    op.drop_constraint(op.f('fk_mcp_agent_jobs_project'), 'mcp_agent_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'mcp_agent_jobs', 'projects', ['project_id'], ['id'])
    op.alter_column('products', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when product was soft deleted (NULL for active products)',
               existing_nullable=True)
    op.alter_column('projects', 'staging_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Staging workflow status: null, staging, staged, cancelled, launching, active',
               existing_comment='Staging workflow status: null, staging, staged, cancelled, launching, active (Handover 0108)',
               existing_nullable=True)
    op.drop_index(op.f('idx_projects_staging_status'), table_name='projects')
    op.drop_index(op.f('idx_projects_status_staging_status'), table_name='projects')
    op.alter_column('tasks', 'agent_job_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Links task to MCPAgentJob for execution tracking',
               existing_nullable=True)
    op.drop_index(op.f('idx_task_assigned'), table_name='tasks')
    op.drop_index(op.f('idx_task_assigned_to_user'), table_name='tasks')
    op.drop_index(op.f('idx_task_tenant_assigned_user'), table_name='tasks')
    op.drop_constraint(op.f('tasks_assigned_to_user_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_agent_job'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_assigned_agent_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'mcp_agent_jobs', ['agent_job_id'], ['job_id'])
    op.drop_column('tasks', 'assigned_to_user_id')
    op.drop_column('tasks', 'assigned_agent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_agent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('assigned_to_user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assigned_agent_id_fkey'), 'tasks', 'agents', ['assigned_agent_id'], ['id'])
    op.create_foreign_key(op.f('fk_task_agent_job'), 'tasks', 'mcp_agent_jobs', ['agent_job_id'], ['job_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tasks_assigned_to_user_id_fkey'), 'tasks', 'users', ['assigned_to_user_id'], ['id'])
    op.create_index(op.f('idx_task_tenant_assigned_user'), 'tasks', ['tenant_key', 'assigned_to_user_id'], unique=False)
    op.create_index(op.f('idx_task_assigned_to_user'), 'tasks', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('idx_task_assigned'), 'tasks', ['assigned_agent_id'], unique=False)
    op.alter_column('tasks', 'agent_job_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Links task to MCPAgentJob for execution tracking',
               existing_nullable=True)
    op.create_index(op.f('idx_projects_status_staging_status'), 'projects', ['status', 'staging_status'], unique=False)
    op.create_index(op.f('idx_projects_staging_status'), 'projects', ['staging_status'], unique=False)
    op.alter_column('projects', 'staging_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Staging workflow status: null, staging, staged, cancelled, launching, active (Handover 0108)',
               existing_comment='Staging workflow status: null, staging, staged, cancelled, launching, active',
               existing_nullable=True)
    op.alter_column('products', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when product was soft deleted (NULL for active products)',
               existing_nullable=True)
    op.drop_constraint(None, 'mcp_agent_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_mcp_agent_jobs_project'), 'mcp_agent_jobs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_mcp_agent_jobs_project_id'), table_name='mcp_agent_jobs')
    op.create_index(op.f('idx_mcp_agent_jobs_job_metadata'), 'mcp_agent_jobs', ['job_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_mcp_agent_jobs_health_status'), 'mcp_agent_jobs', ['tenant_key', 'health_status'], unique=False)
    op.alter_column('mcp_agent_jobs', 'job_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSONB metadata for thin client architecture (Handover 0088). Stores field_priorities, user_id, tool, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('mcp_agent_jobs', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Project ID this job belongs to (Handover 0062)',
               existing_nullable=True)
    op.create_index(op.f('idx_download_tokens_status'), 'download_tokens', ['staging_status', 'expires_at'], unique=False)
    op.alter_column('download_tokens', 'downloaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when download occurred',
               existing_comment='Deprecated: legacy single-use timestamp (not enforced)',
               existing_nullable=True)
    op.alter_column('download_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               comment='Tracks if token has been used (one-time download)',
               existing_comment='Deprecated: legacy one-time download flag (not enforced)',
               existing_nullable=False)
    op.create_index(op.f('idx_agent_templates_system_instructions_gin'), 'agent_templates', ['system_instructions'], unique=False, postgresql_ops={'system_instructions': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('agent_templates', 'cli_tool',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('agent_templates', 'template_content',
               existing_type=sa.TEXT(),
               comment='DEPRECATED (v3.1): Use system_instructions + user_instructions instead. Will be removed in v4.0.',
               existing_comment='DEPRECATED (v3.1): Use system_instructions + user_instructions. Kept for backward compatibility.',
               existing_nullable=False)
    op.alter_column('agent_templates', 'system_instructions',
               existing_type=sa.TEXT(),
               comment='Protected MCP coordination rules (non-editable by users)',
               existing_comment='Protected MCP coordination instructions (non-editable by users)',
               existing_nullable=False)
    op.drop_index(op.f('ix_api_metrics_tenant_key'), table_name='api_metrics')
    op.drop_index('idx_api_metrics_tenant_date', table_name='api_metrics')
    op.drop_table('api_metrics')
    # ### end Alembic commands ###
