<template>
  <v-dialog v-model="isOpen" max-width="900" persistent>
    <v-card>
      <!-- Header -->
      <v-card-title class="d-flex align-center">
        <v-icon class="mr-2" :color="agentColor">mdi-pencil</v-icon>
        Edit {{ agent?.agent_display_name || 'Agent' }} Mission
        <v-spacer />
        <div class="d-flex flex-column align-end mr-2">
          <v-chip size="small" variant="outlined">
            Job: <code data-testid="mission-job-id">{{ agent?.job_id?.slice(0, 8) }}...</code>
          </v-chip>
          <v-chip size="x-small" class="mt-1">
            {{ characterCount.toLocaleString() }} chars
          </v-chip>
        </div>
        <v-btn icon size="small" @click="handleClose" aria-label="Close">
          <v-icon>mdi-close</v-icon>
        </v-btn>
      </v-card-title>

      <v-divider></v-divider>

      <!-- Mission Editor -->
      <v-card-text>
        <v-alert
          v-if="error"
          type="error"
          variant="tonal"
          density="compact"
          closable
          @click:close="error = null"
        >
          {{ error }}
        </v-alert>

        <v-textarea
          v-model="missionText"
          label="Agent Mission"
          placeholder="Enter the mission instructions for this agent..."
          variant="outlined"
          rows="15"
          auto-grow
          :counter="50000"
          :rules="missionRules"
          :loading="loading"
          :disabled="loading"
          class="mission-editor"
        >
          <template #prepend-inner>
            <v-icon>mdi-script-text</v-icon>
          </template>
        </v-textarea>

        <!-- Helper Text -->
        <v-alert type="info" variant="tonal" density="compact" class="mt-2">
          <div class="text-caption">
            <strong>Important:</strong>
            <ul class="pl-4 mt-1">
              <li><strong>Mission is stored at JOB level</strong> (not per execution)</li>
              <li>Changes apply to ALL executions on job {{ agent?.job_id?.slice(0, 8) }}...</li>
              <li>If succession has occurred, all instances share this mission</li>
              <li>Original mission was generated by orchestrator</li>
              <li>You can refine or adjust as needed</li>
            </ul>
          </div>
        </v-alert>

        <!-- Execution Count (if succession has occurred) -->
        <v-alert
          v-if="executionCount > 1"
          type="warning"
          variant="tonal"
          density="compact"
          class="mt-2"
        >
          <div class="text-caption">
            <v-icon size="small" start>mdi-alert</v-icon>
            This job has <strong>{{ executionCount }} executions</strong> (succession has occurred).
            Mission changes will affect all instances.
          </div>
        </v-alert>
      </v-card-text>

      <v-divider></v-divider>

      <!-- Actions -->
      <v-card-actions>
        <v-btn
          variant="text"
          @click="resetToOriginal"
          :disabled="!hasChanges || loading"
        >
          <v-icon start>mdi-restore</v-icon>
          Reset
        </v-btn>
        <v-spacer />
        <v-btn
          variant="text"
          @click="handleClose"
          :disabled="loading"
        >
          Cancel
        </v-btn>
        <v-btn
          color="primary"
          variant="flat"
          @click="saveMission"
          :loading="loading"
          :disabled="!isValid || !hasChanges"
        >
          <v-icon start>mdi-content-save</v-icon>
          Save Mission
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup>
import { ref, computed, watch, getCurrentInstance } from 'vue'
import api from '@/services/api'

const props = defineProps({
  modelValue: {
    type: Boolean,
    required: true,
  },
  agent: {
    type: Object,
    default: null,
  },
})

const emit = defineEmits(['update:modelValue', 'mission-updated'])

// Get API instance (use injected $api if available, otherwise use imported api)
const instance = getCurrentInstance()
const apiClient = instance?.appContext.config.globalProperties.$api || api

// State
const missionText = ref('')
const originalMission = ref('')
const loading = ref(false)
const error = ref(null)

// Computed
const isOpen = computed({
  get: () => props.modelValue,
  set: (val) => emit('update:modelValue', val),
})

const characterCount = computed(() => {
  return missionText.value?.length || 0
})

const hasChanges = computed(() => {
  return missionText.value !== originalMission.value
})

const isValid = computed(() => {
  const trimmed = missionText.value?.trim() || ''
  return trimmed.length > 0 && trimmed.length <= 50000
})

const agentColor = computed(() => {
  // Use background color from agent if available, otherwise default to primary
  return props.agent?.background_color || 'primary'
})

const executionCount = computed(() => {
  return props.agent?.execution_count || 1
})

// Validation rules
const missionRules = [
  (v) => !!v?.trim() || 'Mission is required',
  (v) => (v?.length || 0) <= 50000 || 'Mission must be less than 50,000 characters',
]

// Watch for agent changes and load mission
watch(
  () => props.agent,
  (newAgent) => {
    if (newAgent?.mission) {
      missionText.value = newAgent.mission
      originalMission.value = newAgent.mission
    } else {
      missionText.value = ''
      originalMission.value = ''
    }
    error.value = null
  },
  { immediate: true }
)

// Methods
async function saveMission() {
  if (!isValid.value || !hasChanges.value) return

  loading.value = true
  error.value = null

  try {
    const response = await apiClient.agentJobs.updateMission(props.agent.id, {
      mission: missionText.value,
    })

    if (response.data.success) {
      // Update original mission to reflect saved state
      originalMission.value = missionText.value

      // Emit event for parent to update
      emit('mission-updated', {
        jobId: props.agent.id,
        mission: missionText.value,
      })

      // Close modal
      isOpen.value = false
    }
  } catch (err) {
    console.error('[AgentMissionEditModal] Failed to save mission:', err)
    error.value = err.response?.data?.detail || 'Failed to save mission'
  } finally {
    loading.value = false
  }
}

function resetToOriginal() {
  missionText.value = originalMission.value
  error.value = null
}

function handleClose() {
  if (hasChanges.value) {
    const confirmed = confirm('You have unsaved changes. Are you sure you want to close?')
    if (!confirmed) {
      return
    }
    resetToOriginal()
  }
  isOpen.value = false
}
</script>

<style scoped>
.mission-editor :deep(.v-field__input) {
  font-family: 'Roboto Mono', monospace;
  font-size: 0.875rem;
}

.mission-editor :deep(.v-counter) {
  font-size: 0.75rem;
}
</style>
