"""Add User and APIKey tables for LAN auth

Revision ID: 11b1e4318444
Revises: e2639692ae52
Create Date: 2025-10-07 21:15:33.753235

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "11b1e4318444"
down_revision: Union[str, Sequence[str], None] = "e2639692ae52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_key", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('admin', 'developer', 'viewer')", name="ck_user_role"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_active", "users", ["is_active"], unique=False)
    op.create_index("idx_user_email", "users", ["email"], unique=False)
    op.create_index("idx_user_tenant", "users", ["tenant_key"], unique=False)
    op.create_index("idx_user_username", "users", ["username"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_tenant_key"), "users", ["tenant_key"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_key", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_used", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(is_active = true AND revoked_at IS NULL) OR (is_active = false)", name="ck_apikey_revoked_consistency"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_apikey_active", "api_keys", ["is_active"], unique=False)
    op.create_index("idx_apikey_hash", "api_keys", ["key_hash"], unique=False)
    op.create_index("idx_apikey_permissions_gin", "api_keys", ["permissions"], unique=False, postgresql_using="gin")
    op.create_index("idx_apikey_tenant", "api_keys", ["tenant_key"], unique=False)
    op.create_index("idx_apikey_user", "api_keys", ["user_id"], unique=False)
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_api_keys_tenant_key"), "api_keys", ["tenant_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_keys_tenant_key"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index("idx_apikey_user", table_name="api_keys")
    op.drop_index("idx_apikey_tenant", table_name="api_keys")
    op.drop_index("idx_apikey_permissions_gin", table_name="api_keys", postgresql_using="gin")
    op.drop_index("idx_apikey_hash", table_name="api_keys")
    op.drop_index("idx_apikey_active", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_tenant_key"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("idx_user_username", table_name="users")
    op.drop_index("idx_user_tenant", table_name="users")
    op.drop_index("idx_user_email", table_name="users")
    op.drop_index("idx_user_active", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
