"""Handover 0073 Migration 2: Add project closeout support

Adds columns to the projects table to support orchestrator-driven project closeout
workflow. Enables projects to store final summaries, closeout prompts, execution
timestamps, and checklists for comprehensive project completion tracking.

Key changes:
1. orchestrator_summary: TEXT - Final summary generated by orchestrator agent
2. closeout_prompt: TEXT - Prompt template used for closeout generation
3. closeout_executed_at: TIMESTAMP - When closeout workflow was executed
4. closeout_checklist: JSONB - Structured checklist of closeout tasks

Use cases:
- Orchestrator generates final project summary upon completion
- Track closeout execution for audit/compliance
- Store structured checklists for multi-step closeout workflows
- Maintain closeout prompt history for reproducibility

Revision ID: 20251029_0073_02
Revises: 20251029_0073_01
Create Date: 2025-10-29

Database impact:
  - 4 ADD COLUMN operations (instant in PostgreSQL 11+ with defaults)
  - No data migration required (all columns nullable/defaulted)
Estimated downtime: <1 second
Rollback strategy: Full downgrade support (column drop)
Multi-tenant isolation: Preserved (columns scoped to existing tenant_key)

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy import text


# revision identifiers, used by Alembic
revision: str = '20251029_0073_02'
down_revision: Union[str, Sequence[str], None] = '20251029_0073_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Handover 0073 Migration 2: Add project closeout support.

    This migration enhances the projects table by:
    1. Adding orchestrator_summary for AI-generated project summaries
    2. Adding closeout_prompt for closeout workflow reproducibility
    3. Adding closeout_executed_at for execution timestamp tracking
    4. Adding closeout_checklist for structured task tracking (JSONB)

    Migration characteristics:
    - Idempotent: Safe to run multiple times (column existence checked by Alembic)
    - Isolated: Only affects projects table
    - Zero impact: All columns nullable with sensible defaults
    - Backward compatible: Existing code continues to work without changes
    """

    print("\n" + "=" * 80)
    print("[Handover 0073-02] Adding project closeout support")
    print("=" * 80)

    connection = op.get_bind()

    # STEP 1: Analyze current state
    # =============================
    print("[0073-02] Step 1: Analyzing current projects state...")

    result = connection.execute(text(
        "SELECT COUNT(*) FROM projects"
    ))
    total_projects = result.scalar()
    print(f"[0073-02]   - Total projects in database: {total_projects}")

    result = connection.execute(text(
        "SELECT status, COUNT(*) as count FROM projects GROUP BY status ORDER BY status"
    ))
    status_distribution = result.fetchall()

    print("[0073-02]   Project status distribution:")
    for status, count in status_distribution:
        print(f"[0073-02]     - {status}: {count} project(s)")

    # STEP 2: Add orchestrator_summary column
    # ========================================
    print("[0073-02] Step 2: Adding orchestrator_summary column...")

    op.add_column(
        'projects',
        sa.Column(
            'orchestrator_summary',
            sa.Text(),
            nullable=True,
            comment='AI-generated final summary of project outcomes and deliverables'
        )
    )
    print("[0073-02]   - Added 'orchestrator_summary' column (TEXT, nullable)")

    # STEP 3: Add closeout_prompt column
    # ===================================
    print("[0073-02] Step 3: Adding closeout_prompt column...")

    op.add_column(
        'projects',
        sa.Column(
            'closeout_prompt',
            sa.Text(),
            nullable=True,
            comment='Prompt template used by orchestrator for closeout generation'
        )
    )
    print("[0073-02]   - Added 'closeout_prompt' column (TEXT, nullable)")

    # STEP 4: Add closeout_executed_at column
    # ========================================
    print("[0073-02] Step 4: Adding closeout_executed_at column...")

    op.add_column(
        'projects',
        sa.Column(
            'closeout_executed_at',
            sa.DateTime(timezone=True),
            nullable=True,
            comment='Timestamp when closeout workflow was executed'
        )
    )
    print("[0073-02]   - Added 'closeout_executed_at' column (TIMESTAMP WITH TIME ZONE, nullable)")

    # STEP 5: Add closeout_checklist column (JSONB)
    # ==============================================
    print("[0073-02] Step 5: Adding closeout_checklist column...")

    op.add_column(
        'projects',
        sa.Column(
            'closeout_checklist',
            JSONB,
            nullable=False,
            server_default="'[]'::jsonb",
            comment='Structured checklist of closeout tasks (JSONB array)'
        )
    )
    print("[0073-02]   - Added 'closeout_checklist' column (JSONB, default=[])")

    # STEP 6: Create index for closeout queries
    # ==========================================
    print("[0073-02] Step 6: Creating index for closeout queries...")

    # Index for finding projects with closeout data
    op.create_index(
        'idx_projects_closeout_executed',
        'projects',
        ['closeout_executed_at'],
        postgresql_where=text('closeout_executed_at IS NOT NULL'),
        unique=False
    )
    print("[0073-02]   - Created partial index 'idx_projects_closeout_executed'")

    # STEP 7: Verify migration success
    # =================================
    print("[0073-02] Step 7: Verifying migration...")

    # Check that all projects have default closeout_checklist
    result = connection.execute(text("""
        SELECT COUNT(*)
        FROM projects
        WHERE closeout_checklist IS NULL
    """))
    null_checklists = result.scalar()

    if null_checklists > 0:
        print(f"[0073-02] ERROR: {null_checklists} projects have NULL closeout_checklist!")
        raise Exception("[0073-02] Migration failed: closeout_checklist constraint violation")

    print("[0073-02]   - Verification complete: All projects have closeout_checklist")

    # STEP 8: Show final state
    # ========================
    print("[0073-02] Step 8: Final state summary...")

    result = connection.execute(text("""
        SELECT
            COUNT(*) FILTER (WHERE closeout_executed_at IS NOT NULL) as with_closeout,
            COUNT(*) FILTER (WHERE closeout_executed_at IS NULL) as without_closeout,
            COUNT(*) as total
        FROM projects
    """))
    row = result.fetchone()

    print(f"[0073-02]   Projects ready for closeout tracking:")
    print(f"[0073-02]     - Total projects: {row[2]}")
    print(f"[0073-02]     - With closeout data: {row[0]}")
    print(f"[0073-02]     - Ready for closeout: {row[1]}")

    print("=" * 80)
    print("[Handover 0073-02] Migration completed successfully!")
    print("[0073-02] Project closeout support enabled (4 new columns + index)")
    print("=" * 80 + "\n")


def downgrade() -> None:
    """
    Downgrade migration: Remove project closeout columns.

    This downgrade:
    1. Drops closeout index
    2. Removes all 4 closeout columns

    Data loss:
    - All orchestrator summaries
    - All closeout prompts
    - All closeout execution timestamps
    - All closeout checklists

    Impact: Projects lose closeout tracking capability but remain functional.
    """

    print("\n" + "=" * 80)
    print("[Handover 0073-02] Downgrading: Removing project closeout support")
    print("=" * 80)

    connection = op.get_bind()

    # STEP 1: Check for existing closeout data
    # =========================================
    print("[0073-02 Downgrade] Step 1: Checking for existing closeout data...")

    result = connection.execute(text("""
        SELECT COUNT(*)
        FROM projects
        WHERE closeout_executed_at IS NOT NULL
    """))
    projects_with_closeout = result.scalar()

    if projects_with_closeout > 0:
        print(f"[0073-02] WARNING: {projects_with_closeout} project(s) have closeout data!")
        print("[0073-02] WARNING: This data will be permanently lost after downgrade")

    # STEP 2: Drop closeout index
    # ============================
    print("[0073-02 Downgrade] Step 2: Dropping closeout index...")

    op.drop_index('idx_projects_closeout_executed', table_name='projects')
    print("[0073-02]   - Dropped 'idx_projects_closeout_executed' index")

    # STEP 3: Drop closeout columns
    # ==============================
    print("[0073-02 Downgrade] Step 3: Removing closeout columns...")

    op.drop_column('projects', 'closeout_checklist')
    print("[0073-02]   - Dropped 'closeout_checklist' column")

    op.drop_column('projects', 'closeout_executed_at')
    print("[0073-02]   - Dropped 'closeout_executed_at' column")

    op.drop_column('projects', 'closeout_prompt')
    print("[0073-02]   - Dropped 'closeout_prompt' column")

    op.drop_column('projects', 'orchestrator_summary')
    print("[0073-02]   - Dropped 'orchestrator_summary' column")

    # STEP 4: Verify downgrade success
    # =================================
    print("[0073-02 Downgrade] Step 4: Verifying downgrade...")

    result = connection.execute(text(
        "SELECT COUNT(*) FROM projects"
    ))
    total_projects = result.scalar()

    print(f"[0073-02]   - {total_projects} project(s) remain functional")
    print("[0073-02]   - Closeout tracking disabled")

    print("=" * 80)
    print("[Handover 0073-02] Downgrade completed successfully!")
    print("[0073-02] Project closeout columns removed (4 columns + index)")
    if projects_with_closeout > 0:
        print(f"[0073-02] WARNING: Closeout data lost for {projects_with_closeout} project(s)")
    print("=" * 80 + "\n")
