"""Add converted_to_project_id to tasks (Phase 4)

Revision ID: 2ff9170e5524
Revises: d189b2321f76
Create Date: 2025-10-09 00:18:47.229170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff9170e5524'
down_revision: Union[str, Sequence[str], None] = 'd189b2321f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('converted_to_project_id', sa.String(length=36), nullable=True))
    op.create_index('idx_task_converted_to_project', 'tasks', ['converted_to_project_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'projects', ['converted_to_project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index('idx_task_converted_to_project', table_name='tasks')
    op.drop_column('tasks', 'converted_to_project_id')
    # ### end Alembic commands ###
