"""Initial schema with multi-tenant support

Revision ID: 45abb2fcc00d
Revises:
Create Date: 2025-09-08 23:56:33.149772

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "45abb2fcc00d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_key", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("mission", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("context_budget", sa.Integer(), nullable=True),
        sa.Column("context_used", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_key"),
    )
    op.create_index("idx_project_status", "projects", ["status"], unique=False)
    op.create_index("idx_project_tenant", "projects", ["tenant_key"], unique=False)
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_key", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("mission", sa.Text(), nullable=True),
        sa.Column("context_used", sa.Integer(), nullable=True),
        sa.Column(
            "last_active", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("decommissioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_agent_project_name"),
    )
    op.create_index("idx_agent_project", "agents", ["project_id"], unique=False)
    op.create_index("idx_agent_status", "agents", ["status"], unique=False)
    op.create_index("idx_agent_tenant", "agents", ["tenant_key"], unique=False)
    op.create_table(
        "configurations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_key", sa.String(length=36), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_secret", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_key", "key", name="uq_config_tenant_key"),
    )
    op.create_index("idx_config_category", "configurations", ["category"], unique=False)
    op.create_index("idx_config_tenant", "configurations", ["tenant_key"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_key", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("session_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("objectives", sa.Text(), nullable=True),
        sa.Column("outcomes", sa.Text(), nullable=True),
        sa.Column("decisions", sa.JSON(), nullable=True),
        sa.Column("blockers", sa.JSON(), nullable=True),
        sa.Column("next_steps", sa.JSON(), nullable=True),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "session_number", name="uq_session_project_number"),
    )
    op.create_index("idx_session_project", "sessions", ["project_id"], unique=False)
    op.create_index("idx_session_tenant", "sessions", ["tenant_key"], unique=False)
    op.create_table(
        "visions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_key", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("document_name", sa.String(length=255), nullable=False),
        sa.Column("chunk_number", sa.Integer(), nullable=True),
        sa.Column("total_chunks", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.Column("version", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "document_name", "chunk_number", name="uq_vision_chunk"),
    )
    op.create_index("idx_vision_document", "visions", ["document_name"], unique=False)
    op.create_index("idx_vision_project", "visions", ["project_id"], unique=False)
    op.create_index("idx_vision_tenant", "visions", ["tenant_key"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_key", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("tasks", sa.JSON(), nullable=True),
        sa.Column("scope_boundary", sa.Text(), nullable=True),
        sa.Column("vision_alignment", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_job_agent", "jobs", ["agent_id"], unique=False)
    op.create_index("idx_job_status", "jobs", ["status"], unique=False)
    op.create_index("idx_job_tenant", "jobs", ["tenant_key"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_key", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("from_agent_id", sa.String(length=36), nullable=True),
        sa.Column("to_agents", sa.JSON(), nullable=True),
        sa.Column("message_type", sa.String(length=50), nullable=True),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("acknowledged_by", sa.JSON(), nullable=True),
        sa.Column("completed_by", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["from_agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_message_created", "messages", ["created_at"], unique=False)
    op.create_index("idx_message_priority", "messages", ["priority"], unique=False)
    op.create_index("idx_message_project", "messages", ["project_id"], unique=False)
    op.create_index("idx_message_status", "messages", ["status"], unique=False)
    op.create_index("idx_message_tenant", "messages", ["tenant_key"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_key", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("assigned_agent_id", sa.String(length=36), nullable=True),
        sa.Column("parent_task_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("estimated_effort", sa.Float(), nullable=True),
        sa.Column("actual_effort", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["assigned_agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["parent_task_id"], ["tasks.id"]),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_task_assigned", "tasks", ["assigned_agent_id"], unique=False)
    op.create_index("idx_task_priority", "tasks", ["priority"], unique=False)
    op.create_index("idx_task_project", "tasks", ["project_id"], unique=False)
    op.create_index("idx_task_status", "tasks", ["status"], unique=False)
    op.create_index("idx_task_tenant", "tasks", ["tenant_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_task_tenant", table_name="tasks")
    op.drop_index("idx_task_status", table_name="tasks")
    op.drop_index("idx_task_project", table_name="tasks")
    op.drop_index("idx_task_priority", table_name="tasks")
    op.drop_index("idx_task_assigned", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("idx_message_tenant", table_name="messages")
    op.drop_index("idx_message_status", table_name="messages")
    op.drop_index("idx_message_project", table_name="messages")
    op.drop_index("idx_message_priority", table_name="messages")
    op.drop_index("idx_message_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_job_tenant", table_name="jobs")
    op.drop_index("idx_job_status", table_name="jobs")
    op.drop_index("idx_job_agent", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("idx_vision_tenant", table_name="visions")
    op.drop_index("idx_vision_project", table_name="visions")
    op.drop_index("idx_vision_document", table_name="visions")
    op.drop_table("visions")
    op.drop_index("idx_session_tenant", table_name="sessions")
    op.drop_index("idx_session_project", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("idx_config_tenant", table_name="configurations")
    op.drop_index("idx_config_category", table_name="configurations")
    op.drop_table("configurations")
    op.drop_index("idx_agent_tenant", table_name="agents")
    op.drop_index("idx_agent_status", table_name="agents")
    op.drop_index("idx_agent_project", table_name="agents")
    op.drop_table("agents")
    op.drop_index("idx_project_tenant", table_name="projects")
    op.drop_index("idx_project_status", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
