"""Add nullable project_path to Product model for agent export functionality

Revision ID: 631adb011a79
Revises: 20251029_0072_01
Create Date: 2025-11-02 01:04:44.705328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '631adb011a79'
down_revision: Union[str, Sequence[str], None] = '20251029_0072_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_agent_jobs', sa.Column('instance_number', sa.Integer(), nullable=False, comment='Sequential instance number for orchestrator succession (1, 2, 3, ...)'))
    op.add_column('mcp_agent_jobs', sa.Column('handover_to', sa.String(length=36), nullable=True, comment='UUID of successor orchestrator job (NULL if no handover)'))
    op.add_column('mcp_agent_jobs', sa.Column('handover_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Compressed state transfer for successor orchestrator'))
    op.add_column('mcp_agent_jobs', sa.Column('handover_context_refs', sa.JSON(), nullable=True, comment='Array of context chunk IDs referenced in handover summary'))
    op.add_column('mcp_agent_jobs', sa.Column('succession_reason', sa.String(length=100), nullable=True, comment="Reason for succession: 'context_limit', 'manual', 'phase_transition'"))
    op.add_column('mcp_agent_jobs', sa.Column('context_used', sa.Integer(), nullable=False, comment='Current context window usage in tokens'))
    op.add_column('mcp_agent_jobs', sa.Column('context_budget', sa.Integer(), nullable=False, comment='Maximum context window budget in tokens'))
    op.create_index('idx_agent_jobs_handover', 'mcp_agent_jobs', ['handover_to'], unique=False)
    op.create_index('idx_agent_jobs_instance', 'mcp_agent_jobs', ['project_id', 'agent_type', 'instance_number'], unique=False)
    op.add_column('products', sa.Column('project_path', sa.String(length=500), nullable=True, comment='File system path to product folder (required for agent export)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'project_path')
    op.drop_index('idx_agent_jobs_instance', table_name='mcp_agent_jobs')
    op.drop_index('idx_agent_jobs_handover', table_name='mcp_agent_jobs')
    op.drop_column('mcp_agent_jobs', 'context_budget')
    op.drop_column('mcp_agent_jobs', 'context_used')
    op.drop_column('mcp_agent_jobs', 'succession_reason')
    op.drop_column('mcp_agent_jobs', 'handover_context_refs')
    op.drop_column('mcp_agent_jobs', 'handover_summary')
    op.drop_column('mcp_agent_jobs', 'handover_to')
    op.drop_column('mcp_agent_jobs', 'instance_number')
    # ### end Alembic commands ###
