"""add_last_exported_at_to_agent_templates_handover_0335

Revision ID: 7983bf9c91c9
Revises: ad91f3ce8c9b
Create Date: 2025-12-08 19:55:20.768980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7983bf9c91c9'
down_revision: Union[str, Sequence[str], None] = 'ad91f3ce8c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # Handover 0335: Add last_exported_at column for template staleness tracking
    # Use raw SQL for idempotent ADD COLUMN IF NOT EXISTS
    op.execute("ALTER TABLE agent_templates ADD COLUMN IF NOT EXISTS last_exported_at TIMESTAMP WITH TIME ZONE")

    # Add mission_acknowledged_at if it doesn't exist (missing from baseline)
    conn.execute(sa.text(
        "ALTER TABLE mcp_agent_jobs ADD COLUMN IF NOT EXISTS mission_acknowledged_at TIMESTAMP WITH TIME ZONE"
    ))

    # Add comment to mission_acknowledged_at
    conn.execute(sa.text(
        "COMMENT ON COLUMN mcp_agent_jobs.mission_acknowledged_at IS "
        "'Timestamp when agent first fetched mission via get_agent_mission() or get_orchestrator_instructions()'"
    ))

    # Create indexes if they don't exist (using raw SQL for idempotency)
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_mcp_agent_jobs_composite_status ON mcp_agent_jobs (project_id, status, last_progress_at)"
    ))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_mcp_agent_jobs_health_status ON mcp_agent_jobs (health_status)"
    ))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_mcp_agent_jobs_last_progress ON mcp_agent_jobs (last_progress_at)"
    ))
    op.alter_column('messages', 'result',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('products', 'product_memory',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='360 Memory: GitHub integration, sequential history, context summaries (Handover 0135)',
               existing_comment='360 Memory: GitHub integration, learnings, context summaries (Handover 0135)',
               existing_nullable=False,
               existing_server_default=sa.text('\'{"github": {}, "context": {}, "learnings": []}\'::jsonb'))
    op.alter_column('projects', 'execution_mode',
               existing_type=sa.VARCHAR(length=20),
               comment="Execution mode: 'multi_terminal' (manual) or 'claude_code_cli' (single terminal with Task tool)",
               existing_nullable=False,
               existing_server_default=sa.text("'multi_terminal'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'execution_mode',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Execution mode: 'multi_terminal' (manual) or 'claude_code_cli' (single terminal with Task tool)",
               existing_nullable=False,
               existing_server_default=sa.text("'multi_terminal'::character varying"))
    op.alter_column('products', 'product_memory',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='360 Memory: GitHub integration, learnings, context summaries (Handover 0135)',
               existing_comment='360 Memory: GitHub integration, sequential history, context summaries (Handover 0135)',
               existing_nullable=False,
               existing_server_default=sa.text('\'{"github": {}, "context": {}, "learnings": []}\'::jsonb'))
    op.alter_column('messages', 'result',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index('idx_mcp_agent_jobs_last_progress', table_name='mcp_agent_jobs')
    op.drop_index('idx_mcp_agent_jobs_health_status', table_name='mcp_agent_jobs')
    op.drop_index('idx_mcp_agent_jobs_composite_status', table_name='mcp_agent_jobs')
    op.alter_column('mcp_agent_jobs', 'mission_acknowledged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when agent first fetched mission via get_agent_mission() or get_orchestrator_instructions()',
               existing_nullable=True)

    # Handover 0335: Remove last_exported_at column
    op.drop_column('agent_templates', 'last_exported_at')
    # ### end Alembic commands ###
