"""Add Product model and link to Projects and Tasks

Revision ID: be602279af75
Revises: 08b6b226922d
Create Date: 2025-10-04 00:54:34.612832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be602279af75'
down_revision: Union[str, Sequence[str], None] = '08b6b226922d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vision_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_name', 'products', ['name'], unique=False)
    op.create_index('idx_product_tenant', 'products', ['tenant_key'], unique=False)
    op.create_index(op.f('ix_products_tenant_key'), 'products', ['tenant_key'], unique=False)
    op.add_column('projects', sa.Column('product_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'projects', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'product_id')
    op.drop_index(op.f('ix_products_tenant_key'), table_name='products')
    op.drop_index('idx_product_tenant', table_name='products')
    op.drop_index('idx_product_name', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
