"""unified_baseline_all_tables

Revision ID: caeddfdbb2a0
Revises: 
Create Date: 2025-12-21 04:07:40.129554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'caeddfdbb2a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), server_default='role', nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('system_instructions', sa.Text(), nullable=False, comment='Protected MCP coordination instructions (non-editable by users)'),
    sa.Column('user_instructions', sa.Text(), nullable=True, comment='User-customizable role-specific guidance (editable)'),
    sa.Column('template_content', sa.Text(), nullable=False, comment='DEPRECATED (v3.1): Use system_instructions + user_instructions. Kept for backward compatibility.'),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('behavioral_rules', sa.JSON(), nullable=True),
    sa.Column('success_criteria', sa.JSON(), nullable=True),
    sa.Column('tool', sa.String(length=50), nullable=False),
    sa.Column('cli_tool', sa.String(length=20), nullable=False),
    sa.Column('background_color', sa.String(length=7), nullable=True),
    sa.Column('model', sa.String(length=20), nullable=True),
    sa.Column('tools', sa.String(length=50), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_generation_ms', sa.Float(), nullable=True),
    sa.Column('last_exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', 'version', name='uq_template_product_name_version')
    )
    op.create_index('idx_template_active', 'agent_templates', ['is_active'], unique=False)
    op.create_index('idx_template_category', 'agent_templates', ['category'], unique=False)
    op.create_index('idx_template_product', 'agent_templates', ['product_id'], unique=False)
    op.create_index('idx_template_role', 'agent_templates', ['role'], unique=False)
    op.create_index('idx_template_tenant', 'agent_templates', ['tenant_key'], unique=False)
    op.create_index('idx_template_tool', 'agent_templates', ['tool'], unique=False)
    # Removed duplicate ix_agent_templates_tool (same as idx_template_tool)
    op.create_table('api_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_api_calls', sa.Integer(), nullable=True),
    sa.Column('total_mcp_calls', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_metrics_tenant_date', 'api_metrics', ['tenant_key', 'date'], unique=False)
    op.create_index(op.f('ix_api_metrics_tenant_key'), 'api_metrics', ['tenant_key'], unique=True)
    op.create_table('download_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False, comment='UUID v4 token used in download URL'),
    sa.Column('tenant_key', sa.String(length=36), nullable=False, comment='Tenant key for multi-tenant isolation'),
    sa.Column('download_type', sa.String(length=50), nullable=False, comment="Type of download: 'slash_commands', 'agent_templates'"),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional metadata (filename, file_count, file_size, etc.)'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='Deprecated: legacy one-time download flag (not enforced)'),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True, comment='Deprecated: legacy single-use timestamp (not enforced)'),
    sa.Column('staging_status', sa.String(length=20), nullable=False, comment='Staging lifecycle status: pending|ready|failed'),
    sa.Column('staging_error', sa.Text(), nullable=True, comment='Staging error details when status=failed'),
    sa.Column('download_count', sa.Integer(), nullable=False, comment='Number of successful downloads for this token'),
    sa.Column('last_downloaded_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of most recent successful download'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Token expiry timestamp (15 minutes after creation)'),
    sa.CheckConstraint("download_type IN ('slash_commands', 'agent_templates')", name='ck_download_token_type'),
    sa.CheckConstraint("staging_status IN ('pending', 'ready', 'failed')", name='ck_download_token_staging_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_download_token_expires', 'download_tokens', ['expires_at'], unique=False)
    op.create_index('idx_download_token_tenant', 'download_tokens', ['tenant_key'], unique=False)
    op.create_index('idx_download_token_tenant_type', 'download_tokens', ['tenant_key', 'download_type'], unique=False)
    op.create_index('idx_download_token_token', 'download_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_download_tokens_tenant_key'), 'download_tokens', ['tenant_key'], unique=False)
    op.create_index(op.f('ix_download_tokens_token'), 'download_tokens', ['token'], unique=True)
    op.create_table('git_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('remote_name', sa.String(length=50), nullable=True),
    sa.Column('auth_method', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('ssh_key_path', sa.String(length=500), nullable=True),
    sa.Column('ssh_key_encrypted', sa.Text(), nullable=True),
    sa.Column('auto_commit', sa.Boolean(), nullable=True),
    sa.Column('auto_push', sa.Boolean(), nullable=True),
    sa.Column('commit_message_template', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('webhook_events', sa.JSON(), nullable=True),
    sa.Column('ignore_patterns', sa.JSON(), nullable=True),
    sa.Column('git_config_options', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_commit_hash', sa.String(length=40), nullable=True),
    sa.Column('last_push_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.CheckConstraint("auth_method IN ('https', 'ssh', 'token')", name='ck_git_config_auth_method'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', name='uq_git_config_product')
    )
    op.create_index('idx_git_config_active', 'git_configs', ['is_active'], unique=False)
    op.create_index('idx_git_config_auth', 'git_configs', ['auth_method'], unique=False)
    op.create_index('idx_git_config_product', 'git_configs', ['product_id'], unique=False)
    op.create_index('idx_git_config_tenant', 'git_configs', ['tenant_key'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('tasks', sa.JSON(), nullable=True),
    sa.Column('scope_boundary', sa.Text(), nullable=True),
    sa.Column('vision_alignment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_status', 'jobs', ['status'], unique=False)
    op.create_index('idx_job_tenant', 'jobs', ['tenant_key'], unique=False)
    op.create_table('optimization_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('params_size', sa.Integer(), nullable=False),
    sa.Column('result_size', sa.Integer(), nullable=False),
    sa.Column('optimized', sa.Boolean(), nullable=False),
    sa.Column('tokens_saved', sa.Integer(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("operation_type IN ('file_read', 'symbol_search', 'symbol_replace', 'pattern_search', 'directory_list')", name='ck_optimization_metric_operation_type'),
    sa.CheckConstraint('params_size >= 0', name='ck_optimization_metric_params_size'),
    sa.CheckConstraint('result_size >= 0', name='ck_optimization_metric_result_size'),
    sa.CheckConstraint('tokens_saved >= 0', name='ck_optimization_metric_tokens_saved'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_optimization_metric_date', 'optimization_metrics', ['created_at'], unique=False)
    op.create_index('idx_optimization_metric_optimized', 'optimization_metrics', ['optimized'], unique=False)
    op.create_index('idx_optimization_metric_tenant', 'optimization_metrics', ['tenant_key'], unique=False)
    op.create_index('idx_optimization_metric_type', 'optimization_metrics', ['operation_type'], unique=False)
    op.create_index(op.f('ix_optimization_metrics_tenant_key'), 'optimization_metrics', ['tenant_key'], unique=False)
    op.create_table('optimization_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('max_answer_chars', sa.Integer(), nullable=False),
    sa.Column('prefer_symbolic', sa.Boolean(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=False),
    sa.Column('context_filter', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("operation_type IN ('file_read', 'symbol_search', 'symbol_replace', 'pattern_search', 'directory_list')", name='ck_optimization_rule_operation_type'),
    sa.CheckConstraint('max_answer_chars > 0', name='ck_optimization_rule_max_chars'),
    sa.CheckConstraint('priority >= 0', name='ck_optimization_rule_priority'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_optimization_rule_active', 'optimization_rules', ['is_active'], unique=False)
    op.create_index('idx_optimization_rule_tenant', 'optimization_rules', ['tenant_key'], unique=False)
    op.create_index('idx_optimization_rule_type', 'optimization_rules', ['operation_type'], unique=False)
    op.create_index(op.f('ix_optimization_rules_tenant_key'), 'optimization_rules', ['tenant_key'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_path', sa.String(length=500), nullable=True, comment='File system path to product folder (required for agent export)'),
    sa.Column('quality_standards', sa.Text(), nullable=True, comment='Quality standards and testing expectations'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when product was soft deleted (NULL for active products)'),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active product for token estimation and mission planning (one per tenant)'),
    sa.Column('config_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Rich project configuration: architecture, tech_stack, features, etc.'),
    sa.Column('product_memory', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"github": {}, "sequential_history": [], "context": {}}\'::jsonb'), nullable=False, comment='360 Memory: GitHub integration, sequential history, context summaries (Handover 0135)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_config_data_gin', 'products', ['config_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_product_memory_gin', 'products', ['product_memory'], unique=False, postgresql_using='gin')
    op.create_index('idx_product_name', 'products', ['name'], unique=False)
    op.create_index('idx_product_single_active_per_tenant', 'products', ['tenant_key'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_product_tenant', 'products', ['tenant_key'], unique=False)
    op.create_index('idx_products_deleted_at', 'products', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index(op.f('ix_products_tenant_key'), 'products', ['tenant_key'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('settings_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_key', 'category', name='uq_settings_tenant_category')
    )
    op.create_index('idx_settings_category', 'settings', ['category'], unique=False)
    op.create_index('idx_settings_tenant', 'settings', ['tenant_key'], unique=False)
    op.create_index(op.f('ix_settings_tenant_key'), 'settings', ['tenant_key'], unique=False)
    op.create_table('setup_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('database_initialized', sa.Boolean(), nullable=False),
    sa.Column('database_initialized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('setup_version', sa.String(length=20), nullable=True),
    sa.Column('database_version', sa.String(length=20), nullable=True),
    sa.Column('python_version', sa.String(length=20), nullable=True),
    sa.Column('node_version', sa.String(length=20), nullable=True),
    sa.Column('first_admin_created', sa.Boolean(), nullable=False, comment='True after first admin account created - prevents duplicate admin creation attacks'),
    sa.Column('first_admin_created_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when first admin account was created'),
    sa.Column('features_configured', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Nested dict of configured features: {database: true, api: {enabled: true, port: 7272}}'),
    sa.Column('tools_enabled', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of enabled MCP tool names'),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot of config.yaml at setup completion'),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('validation_failures', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of validation failure messages'),
    sa.Column('validation_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of validation warning messages'),
    sa.Column('last_validation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('installer_version', sa.String(length=20), nullable=True),
    sa.Column('install_mode', sa.String(length=20), nullable=True, comment='Installation mode: localhost, server, lan, wan'),
    sa.Column('install_path', sa.Text(), nullable=True, comment='Installation directory path'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("database_version IS NULL OR database_version ~ '^[0-9]+(\\.([0-9]+|[0-9]+\\.[0-9]+))?$'", name='ck_database_version_format'),
    sa.CheckConstraint("install_mode IS NULL OR install_mode IN ('localhost', 'server', 'lan', 'wan')", name='ck_install_mode_values'),
    sa.CheckConstraint("setup_version IS NULL OR setup_version ~ '^[0-9]+\\.[0-9]+\\.[0-9]+(-[a-zA-Z0-9\\.\\-]+)?$'", name='ck_setup_version_format'),
    sa.CheckConstraint('(database_initialized = false) OR (database_initialized = true AND database_initialized_at IS NOT NULL)', name='ck_database_initialized_at_required'),
    sa.CheckConstraint('(first_admin_created = false) OR (first_admin_created = true AND first_admin_created_at IS NOT NULL)', name='ck_first_admin_created_at_required'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_setup_database_incomplete', 'setup_state', ['tenant_key', 'database_initialized'], unique=False, postgresql_where='database_initialized = false')
    op.create_index('idx_setup_database_initialized', 'setup_state', ['database_initialized'], unique=False)
    op.create_index('idx_setup_features_gin', 'setup_state', ['features_configured'], unique=False, postgresql_using='gin')
    op.create_index('idx_setup_fresh_install', 'setup_state', ['tenant_key', 'first_admin_created'], unique=False, postgresql_where='first_admin_created = false')
    op.create_index('idx_setup_mode', 'setup_state', ['install_mode'], unique=False)
    op.create_index('idx_setup_tenant', 'setup_state', ['tenant_key'], unique=False)
    op.create_index('idx_setup_tools_gin', 'setup_state', ['tools_enabled'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_setup_state_database_initialized'), 'setup_state', ['database_initialized'], unique=False)
    op.create_index(op.f('ix_setup_state_first_admin_created'), 'setup_state', ['first_admin_created'], unique=False)
    op.create_index(op.f('ix_setup_state_tenant_key'), 'setup_state', ['tenant_key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('recovery_pin_hash', sa.String(length=255), nullable=True, comment='Bcrypt hash of 4-digit recovery PIN for password reset'),
    sa.Column('failed_pin_attempts', sa.Integer(), nullable=False, comment='Number of failed PIN verification attempts (rate limiting)'),
    sa.Column('pin_lockout_until', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when PIN lockout expires (15 minutes after 5 failed attempts)'),
    sa.Column('must_change_password', sa.Boolean(), nullable=False, comment='Force user to change password on next login (new users, admin reset)'),
    sa.Column('must_set_pin', sa.Boolean(), nullable=False, comment='Force user to set recovery PIN on next login (new users)'),
    sa.Column('is_system_user', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('field_priority_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='User-customizable field priority for agent mission generation'),
    sa.Column('depth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='User depth configuration for context granularity (Handover 0314)'),
    sa.CheckConstraint("role IN ('admin', 'developer', 'viewer')", name='ck_user_role'),
    sa.CheckConstraint('failed_pin_attempts >= 0', name='ck_user_pin_attempts_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_pin_lockout', 'users', ['pin_lockout_until'], unique=False)
    op.create_index('idx_user_system', 'users', ['is_system_user'], unique=False)
    op.create_index('idx_user_tenant', 'users', ['tenant_key'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_key'), 'users', ['tenant_key'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(is_active = true AND revoked_at IS NULL) OR (is_active = false)', name='ck_apikey_revoked_consistency'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_apikey_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('idx_apikey_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_apikey_permissions_gin', 'api_keys', ['permissions'], unique=False, postgresql_using='gin')
    op.create_index('idx_apikey_tenant', 'api_keys', ['tenant_key'], unique=False)
    op.create_index('idx_apikey_user', 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_tenant_key'), 'api_keys', ['tenant_key'], unique=False)
    op.create_table('mcp_context_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('context_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=False, comment='Original full context before condensation'),
    sa.Column('condensed_mission', sa.Text(), nullable=False, comment='Orchestrator-generated condensed mission'),
    sa.Column('full_token_count', sa.Integer(), nullable=True),
    sa.Column('condensed_token_count', sa.Integer(), nullable=True),
    sa.Column('reduction_percent', sa.Float(), nullable=True, comment='Context prioritization percentage achieved'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('context_id')
    )
    op.create_index('idx_mcp_summary_context_id', 'mcp_context_summary', ['context_id'], unique=False)
    op.create_index('idx_mcp_summary_tenant_product', 'mcp_context_summary', ['tenant_key', 'product_id'], unique=False)
    op.create_index(op.f('ix_mcp_context_summary_tenant_key'), 'mcp_context_summary', ['tenant_key'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=6), nullable=False, comment='6-character alphanumeric project identifier (e.g., A1B2C3)'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mission', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('staging_status', sa.String(length=50), nullable=True, comment='Staging workflow status: null, staging, staged, cancelled, launching, active'),
    sa.Column('context_budget', sa.Integer(), nullable=True),
    sa.Column('context_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True, comment='First activation timestamp (only set once on first activation)'),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when project was last paused/deactivated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when project was soft deleted (NULL for active projects)'),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('orchestrator_summary', sa.Text(), nullable=True, comment='AI-generated final summary of project outcomes and deliverables'),
    sa.Column('closeout_prompt', sa.Text(), nullable=True, comment='Prompt template used by orchestrator for closeout generation'),
    sa.Column('closeout_executed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when closeout workflow was executed'),
    sa.Column('closeout_checklist', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Structured checklist of closeout tasks (JSONB array)'),
    sa.Column('execution_mode', sa.String(length=20), server_default=sa.text("'multi_terminal'"), nullable=False, comment="Execution mode: 'multi_terminal' (manual) or 'claude_code_cli' (single terminal with Task tool)"),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_single_active_per_product', 'projects', ['product_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('idx_project_status', 'projects', ['status'], unique=False)
    op.create_index('idx_project_tenant', 'projects', ['tenant_key'], unique=False)
    op.create_index('idx_projects_closeout_executed', 'projects', ['closeout_executed_at'], unique=False, postgresql_where=sa.text('closeout_executed_at IS NOT NULL'))
    op.create_index('idx_projects_deleted_at', 'projects', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index(op.f('ix_projects_alias'), 'projects', ['alias'], unique=True)
    op.create_table('template_archives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('system_instructions', sa.Text(), nullable=True),
    sa.Column('user_instructions', sa.Text(), nullable=True),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('behavioral_rules', sa.JSON(), nullable=True),
    sa.Column('success_criteria', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('archive_reason', sa.String(length=255), nullable=True),
    sa.Column('archive_type', sa.String(length=20), nullable=True),
    sa.Column('archived_by', sa.String(length=100), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('usage_count_at_archive', sa.Integer(), nullable=True),
    sa.Column('avg_generation_ms_at_archive', sa.Float(), nullable=True),
    sa.Column('is_restorable', sa.Boolean(), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by', sa.String(length=100), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['agent_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_archive_date', 'template_archives', ['archived_at'], unique=False)
    op.create_index('idx_archive_product', 'template_archives', ['product_id'], unique=False)
    op.create_index('idx_archive_template', 'template_archives', ['template_id'], unique=False)
    op.create_index('idx_archive_tenant', 'template_archives', ['tenant_key'], unique=False)
    op.create_index('idx_archive_version', 'template_archives', ['version'], unique=False)
    # NOTE: template_augmentations table REMOVED (Handover 0423 - dead code cleanup)
    op.create_table('vision_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False, comment="User-friendly document name (e.g., 'Product Architecture', 'API Design')"),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment='Document category: vision, architecture, features, setup, api, testing, deployment, custom'),
    sa.Column('vision_path', sa.String(length=500), nullable=True, comment='File path to vision document (file-based or hybrid storage)'),
    sa.Column('vision_document', sa.Text(), nullable=True, comment='Inline vision text (inline or hybrid storage)'),
    sa.Column('storage_type', sa.String(length=20), nullable=False, comment="Storage mode: 'file', 'inline', or 'hybrid'"),
    sa.Column('chunked', sa.Boolean(), nullable=False, comment='Has document been chunked into mcp_context_index for RAG'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='Number of chunks created for this document'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='Estimated total tokens in document'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='Original file size in bytes (NULL for inline content without file)'),
    sa.Column('is_summarized', sa.Boolean(), nullable=False, comment='Has document been summarized using LSA algorithm'),
    sa.Column('original_token_count', sa.Integer(), nullable=True, comment='Original document token count before summarization'),
    sa.Column('summary_light', sa.Text(), nullable=True, comment='Light summary (~33% of original, ~13K tokens for 40K doc)'),
    sa.Column('summary_medium', sa.Text(), nullable=True, comment='Medium summary (~66% of original, ~26K tokens for 40K doc)'),
    sa.Column('summary_light_tokens', sa.Integer(), nullable=True, comment='Actual token count in light summary'),
    sa.Column('summary_medium_tokens', sa.Integer(), nullable=True, comment='Actual token count in medium summary'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Document version using semantic versioning'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA-256 hash of document content for change detection'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active documents are used for context; inactive are archived'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Display order in UI (lower numbers first)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True, comment='Additional metadata: author, tags, source_url, etc.'),
    sa.CheckConstraint("(storage_type = 'file' AND vision_path IS NOT NULL) OR (storage_type = 'inline' AND vision_document IS NOT NULL) OR (storage_type = 'hybrid' AND vision_path IS NOT NULL AND vision_document IS NOT NULL)", name='ck_vision_doc_storage_consistency'),
    sa.CheckConstraint("document_type IN ('vision', 'architecture', 'features', 'setup', 'api', 'testing', 'deployment', 'custom')", name='ck_vision_doc_document_type'),
    sa.CheckConstraint("storage_type IN ('file', 'inline', 'hybrid')", name='ck_vision_doc_storage_type'),
    sa.CheckConstraint('(chunked = false AND chunk_count = 0) OR (chunked = true AND chunk_count > 0)', name='ck_vision_doc_chunked_consistency'),
    sa.CheckConstraint('chunk_count >= 0', name='ck_vision_doc_chunk_count'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'document_name', name='uq_vision_doc_product_name')
    )
    op.create_index('idx_vision_doc_active', 'vision_documents', ['is_active'], unique=False)
    op.create_index('idx_vision_doc_chunked', 'vision_documents', ['chunked'], unique=False)
    op.create_index('idx_vision_doc_product', 'vision_documents', ['product_id'], unique=False)
    op.create_index('idx_vision_doc_product_active', 'vision_documents', ['product_id', 'is_active', 'display_order'], unique=False)
    op.create_index('idx_vision_doc_product_type', 'vision_documents', ['product_id', 'document_type'], unique=False)
    op.create_index('idx_vision_doc_tenant', 'vision_documents', ['tenant_key'], unique=False)
    op.create_index('idx_vision_doc_tenant_product', 'vision_documents', ['tenant_key', 'product_id'], unique=False)
    op.create_index('idx_vision_doc_type', 'vision_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_vision_documents_tenant_key'), 'vision_documents', ['tenant_key'], unique=False)
    op.create_table('agent_interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sub_agent_name', sa.String(length=100), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('mission', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.CheckConstraint("interaction_type IN ('SPAWN', 'COMPLETE', 'ERROR')", name='ck_interaction_type'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interaction_created', 'agent_interactions', ['created_at'], unique=False)
    op.create_index('idx_interaction_project', 'agent_interactions', ['project_id'], unique=False)
    op.create_index('idx_interaction_tenant', 'agent_interactions', ['tenant_key'], unique=False)
    op.create_index('idx_interaction_type', 'agent_interactions', ['interaction_type'], unique=False)
    op.create_table('agent_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True, comment='Project this job belongs to (Handover 0062)'),
    sa.Column('mission', sa.Text(), nullable=False, comment='Agent mission/instructions'),
    sa.Column('job_type', sa.String(length=100), nullable=False, comment='Job type: orchestrator, analyzer, implementer, tester, etc.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Job status: active, completed, cancelled'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Job-level metadata (field priorities, depth config, etc.)'),
    sa.Column('template_id', sa.String(length=36), nullable=True, comment='Template used to create this job (if any)'),
    sa.CheckConstraint("status IN ('active', 'completed', 'cancelled')", name='ck_agent_job_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['agent_templates.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_agent_jobs_project', 'agent_jobs', ['project_id'], unique=False)
    op.create_index('idx_agent_jobs_status', 'agent_jobs', ['status'], unique=False)
    op.create_index('idx_agent_jobs_tenant', 'agent_jobs', ['tenant_key'], unique=False)
    op.create_index('idx_agent_jobs_tenant_project', 'agent_jobs', ['tenant_key', 'project_id'], unique=False)
    # Removed duplicate ix_agent_jobs_project_id (same as idx_agent_jobs_project)
    # Removed duplicate ix_agent_jobs_tenant_key (same as idx_agent_jobs_tenant)
    op.create_table('configurations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_key', 'key', name='uq_config_tenant_key')
    )
    op.create_index('idx_config_category', 'configurations', ['category'], unique=False)
    op.create_index('idx_config_tenant', 'configurations', ['tenant_key'], unique=False)
    op.create_table('context_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('index_type', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('section_name', sa.String(length=255), nullable=True),
    sa.Column('chunk_numbers', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('full_path', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'document_name', 'section_name', name='uq_context_index')
    )
    op.create_index('idx_context_doc', 'context_index', ['document_name'], unique=False)
    op.create_index('idx_context_tenant', 'context_index', ['tenant_key'], unique=False)
    op.create_index('idx_context_type', 'context_index', ['index_type'], unique=False)
    op.create_table('discovery_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('path_key', sa.String(length=50), nullable=False),
    sa.Column('path_value', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'path_key', name='uq_discovery_path')
    )
    op.create_index('idx_discovery_project', 'discovery_config', ['project_id'], unique=False)
    op.create_index('idx_discovery_tenant', 'discovery_config', ['tenant_key'], unique=False)
    op.create_table('git_commits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=False),
    sa.Column('files_changed', sa.JSON(), nullable=True),
    sa.Column('insertions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('commit_type', sa.String(length=50), nullable=True),
    sa.Column('push_status', sa.String(length=20), nullable=True),
    sa.Column('push_error', sa.Text(), nullable=True),
    sa.Column('webhook_triggered', sa.Boolean(), nullable=True),
    sa.Column('webhook_response', sa.JSON(), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.CheckConstraint("push_status IN ('pending', 'pushed', 'failed')", name='ck_git_commit_push_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commit_hash')
    )
    op.create_index('idx_git_commit_date', 'git_commits', ['committed_at'], unique=False)
    op.create_index('idx_git_commit_hash', 'git_commits', ['commit_hash'], unique=False)
    op.create_index('idx_git_commit_product', 'git_commits', ['product_id'], unique=False)
    op.create_index('idx_git_commit_project', 'git_commits', ['project_id'], unique=False)
    op.create_index('idx_git_commit_tenant', 'git_commits', ['tenant_key'], unique=False)
    op.create_index('idx_git_commit_trigger', 'git_commits', ['triggered_by'], unique=False)
    op.create_table('large_document_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_path', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('total_size', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'document_path', name='uq_large_doc_path')
    )
    op.create_index('idx_large_doc_tenant', 'large_document_index', ['tenant_key'], unique=False)
    op.create_table('mcp_agent_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True, comment='Project ID this job belongs to (Handover 0062)'),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False, comment='Agent type: orchestrator, analyzer, implementer, tester, etc.'),
    sa.Column('mission', sa.Text(), nullable=False, comment='Agent mission/instructions'),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('failure_reason', sa.String(length=50), nullable=True, comment='Reason for failure: error, timeout, system_error (Handover 0113)'),
    sa.Column('spawned_by', sa.String(length=36), nullable=True, comment='Agent ID that spawned this job'),
    sa.Column('context_chunks', sa.JSON(), nullable=True, comment='Array of chunk_ids from mcp_context_index for context loading'),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of message objects for agent communication'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False, comment='Job completion progress (0-100%)'),
    sa.Column('block_reason', sa.Text(), nullable=True, comment='Explanation of why job is blocked (NULL if not blocked)'),
    sa.Column('current_task', sa.Text(), nullable=True, comment='Description of current task being executed'),
    sa.Column('estimated_completion', sa.DateTime(timezone=True), nullable=True, comment='Estimated completion timestamp'),
    sa.Column('tool_type', sa.String(length=20), nullable=False, comment='AI coding tool assigned to this agent job (claude-code, codex, gemini, universal)'),
    sa.Column('agent_name', sa.String(length=255), nullable=True, comment='Human-readable agent display name (e.g., Backend Agent, Database Agent)'),
    sa.Column('instance_number', sa.Integer(), nullable=False, comment='Sequential instance number for orchestrator succession (1, 2, 3, ...)'),
    sa.Column('handover_to', sa.String(length=36), nullable=True, comment='UUID of successor orchestrator job (NULL if no handover)'),
    sa.Column('handover_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Compressed state transfer for successor orchestrator'),
    sa.Column('handover_context_refs', sa.JSON(), nullable=True, comment='Array of context chunk IDs referenced in handover summary'),
    sa.Column('succession_reason', sa.String(length=100), nullable=True, comment="Reason for succession: 'context_limit', 'manual', 'phase_transition'"),
    sa.Column('context_used', sa.Integer(), nullable=False, comment='Current context window usage in tokens'),
    sa.Column('context_budget', sa.Integer(), nullable=False, comment='Maximum context window budget in tokens'),
    sa.Column('job_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSONB metadata for thin client architecture (Handover 0088). Stores field_priorities, user_id, tool, etc.'),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last health check scan'),
    sa.Column('health_status', sa.String(length=20), nullable=False, comment='Health state: unknown, healthy, warning, critical, timeout'),
    sa.Column('health_failure_count', sa.Integer(), nullable=False, comment='Consecutive health check failures'),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last progress update from agent (Handover 0107)'),
    sa.Column('last_message_check_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last message queue check (Handover 0107)'),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when agent job was decommissioned (Handover 0113)'),
    sa.Column('mission_acknowledged_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when agent first fetched mission via get_agent_mission() or get_orchestrator_instructions()'),
    sa.Column('template_id', sa.String(length=36), nullable=True, comment='Agent template ID this job was spawned from (Handover 0244a)'),
    sa.CheckConstraint("failure_reason IS NULL OR failure_reason IN ('error', 'timeout', 'system_error')", name='ck_mcp_agent_job_failure_reason'),
    sa.CheckConstraint("health_status IN ('unknown', 'healthy', 'warning', 'critical', 'timeout')", name='ck_mcp_agent_job_health_status'),
    sa.CheckConstraint("status IN ('waiting', 'working', 'blocked', 'complete', 'failed', 'cancelled', 'decommissioned')", name='ck_mcp_agent_job_status'),
    sa.CheckConstraint("succession_reason IS NULL OR succession_reason IN ('context_limit', 'manual', 'phase_transition')", name='ck_mcp_agent_job_succession_reason'),
    sa.CheckConstraint("tool_type IN ('claude-code', 'codex', 'gemini', 'universal')", name='ck_mcp_agent_job_tool_type'),
    sa.CheckConstraint('context_used >= 0 AND context_used <= context_budget', name='ck_mcp_agent_job_context_usage'),
    sa.CheckConstraint('health_failure_count >= 0', name='ck_mcp_agent_job_health_failure_count'),
    sa.CheckConstraint('instance_number >= 1', name='ck_mcp_agent_job_instance_positive'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_mcp_agent_job_progress_range'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['agent_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_agent_jobs_handover', 'mcp_agent_jobs', ['handover_to'], unique=False)
    op.create_index('idx_agent_jobs_instance', 'mcp_agent_jobs', ['project_id', 'agent_type', 'instance_number'], unique=False)
    op.create_index('idx_mcp_agent_jobs_composite_status', 'mcp_agent_jobs', ['project_id', 'status', 'last_progress_at'], unique=False)
    op.create_index('idx_mcp_agent_jobs_health_status', 'mcp_agent_jobs', ['health_status'], unique=False)
    op.create_index('idx_mcp_agent_jobs_job_id', 'mcp_agent_jobs', ['job_id'], unique=False)
    op.create_index('idx_mcp_agent_jobs_last_progress', 'mcp_agent_jobs', ['last_progress_at'], unique=False)
    op.create_index('idx_mcp_agent_jobs_project', 'mcp_agent_jobs', ['project_id'], unique=False)
    op.create_index('idx_mcp_agent_jobs_tenant_project', 'mcp_agent_jobs', ['tenant_key', 'project_id'], unique=False)
    op.create_index('idx_mcp_agent_jobs_tenant_status', 'mcp_agent_jobs', ['tenant_key', 'status'], unique=False)
    op.create_index('idx_mcp_agent_jobs_tenant_tool', 'mcp_agent_jobs', ['tenant_key', 'tool_type'], unique=False)
    op.create_index('idx_mcp_agent_jobs_tenant_type', 'mcp_agent_jobs', ['tenant_key', 'agent_type'], unique=False)
    op.create_index(op.f('ix_mcp_agent_jobs_project_id'), 'mcp_agent_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_mcp_agent_jobs_tenant_key'), 'mcp_agent_jobs', ['tenant_key'], unique=False)
    op.create_table('mcp_context_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('vision_document_id', sa.String(length=36), nullable=True, comment='Link to specific vision document (NULL for legacy product-level chunks)'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True, comment='Optional LLM-generated summary (NULL for Phase 1 non-LLM chunking)'),
    sa.Column('keywords', sa.JSON(), nullable=True, comment='Array of keyword strings extracted via regex or LLM'),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=True, comment='Sequential chunk number for maintaining document order'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('searchable_vector', postgresql.TSVECTOR(), nullable=True, comment='Full-text search vector for fast keyword lookup'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vision_document_id'], ['vision_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    op.create_index('idx_mcp_context_chunk_id', 'mcp_context_index', ['chunk_id'], unique=False)
    op.create_index('idx_mcp_context_product_vision_doc', 'mcp_context_index', ['product_id', 'vision_document_id'], unique=False)
    op.create_index('idx_mcp_context_searchable', 'mcp_context_index', ['searchable_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_mcp_context_tenant_product', 'mcp_context_index', ['tenant_key', 'product_id'], unique=False)
    op.create_index('idx_mcp_context_vision_doc', 'mcp_context_index', ['vision_document_id'], unique=False)
    op.create_index(op.f('ix_mcp_context_index_tenant_key'), 'mcp_context_index', ['tenant_key'], unique=False)
    op.create_table('mcp_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('api_key_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('session_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='MCP protocol state: client_info, capabilities, tool_call_history'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcp_session_api_key', 'mcp_sessions', ['api_key_id'], unique=False)
    op.create_index('idx_mcp_session_cleanup', 'mcp_sessions', ['expires_at', 'last_accessed'], unique=False)
    op.create_index('idx_mcp_session_data_gin', 'mcp_sessions', ['session_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_mcp_session_expires', 'mcp_sessions', ['expires_at'], unique=False)
    op.create_index('idx_mcp_session_last_accessed', 'mcp_sessions', ['last_accessed'], unique=False)
    op.create_index('idx_mcp_session_tenant', 'mcp_sessions', ['tenant_key'], unique=False)
    op.create_index(op.f('ix_mcp_sessions_session_id'), 'mcp_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_mcp_sessions_tenant_key'), 'mcp_sessions', ['tenant_key'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('to_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('acknowledged_by', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_by', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('backoff_seconds', sa.Integer(), nullable=True),
    sa.Column('circuit_breaker_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_created', 'messages', ['created_at'], unique=False)
    op.create_index('idx_message_priority', 'messages', ['priority'], unique=False)
    op.create_index('idx_message_project', 'messages', ['project_id'], unique=False)
    op.create_index('idx_message_status', 'messages', ['status'], unique=False)
    op.create_index('idx_message_tenant', 'messages', ['tenant_key'], unique=False)
    # NOTE: sessions table REMOVED (Handover 0423 - dead code cleanup)
    op.create_table('template_usage_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('generation_ms', sa.Integer(), nullable=True),
    sa.Column('variables_used', sa.JSON(), nullable=True),
    sa.Column('augmentations_applied', sa.JSON(), nullable=True),
    sa.Column('agent_completed', sa.Boolean(), nullable=True),
    sa.Column('agent_success_rate', sa.Float(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['agent_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_date', 'template_usage_stats', ['used_at'], unique=False)
    op.create_index('idx_usage_project', 'template_usage_stats', ['project_id'], unique=False)
    op.create_index('idx_usage_template', 'template_usage_stats', ['template_id'], unique=False)
    op.create_index('idx_usage_tenant', 'template_usage_stats', ['tenant_key'], unique=False)
    op.create_table('visions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('chunk_number', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('boundary_type', sa.String(length=20), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'document_name', 'chunk_number', name='uq_vision_chunk')
    )
    op.create_index('idx_vision_document', 'visions', ['document_name'], unique=False)
    op.create_index('idx_vision_project', 'visions', ['project_id'], unique=False)
    op.create_index('idx_vision_tenant', 'visions', ['tenant_key'], unique=False)
    op.create_table('agent_executions',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='Foreign key to parent AgentJob'),
    sa.Column('tenant_key', sa.String(length=50), nullable=False),
    sa.Column('agent_display_name', sa.String(length=100), nullable=False, comment='Human-readable display name for UI'),
    sa.Column('instance_number', sa.Integer(), nullable=False, comment='Sequential instance number for succession (1, 2, 3, ...)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Execution status: waiting, working, blocked, complete, failed, cancelled, decommissioned'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spawned_by', sa.String(length=36), nullable=True, comment='Agent ID of parent executor (clear: agent, not job)'),
    sa.Column('succeeded_by', sa.String(length=36), nullable=True, comment='Agent ID of successor executor (clear: agent, not job)'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='Execution completion progress (0-100%)'),
    sa.Column('current_task', sa.Text(), nullable=True, comment='Description of current task'),
    sa.Column('block_reason', sa.Text(), nullable=True, comment='Explanation of why execution is blocked (NULL if not blocked)'),
    sa.Column('health_status', sa.String(length=20), nullable=False, comment='Health state: unknown, healthy, warning, critical, timeout'),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_failure_count', sa.Integer(), nullable=False),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last progress update from agent'),
    sa.Column('last_message_check_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last message queue check'),
    sa.Column('mission_acknowledged_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when agent first fetched mission'),
    sa.Column('tool_type', sa.String(length=20), nullable=False, comment='AI coding tool assigned (claude-code, codex, gemini, universal)'),
    sa.Column('context_used', sa.Integer(), nullable=False, comment='Current context window usage in tokens'),
    sa.Column('context_budget', sa.Integer(), nullable=False, comment='Maximum context window budget in tokens'),
    sa.Column('succession_reason', sa.String(length=100), nullable=True, comment='Reason for succession: context_limit, manual, phase_transition'),
    sa.Column('handover_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Compressed state transfer for successor orchestrator'),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='DEPRECATED - Use counter columns instead. Will be removed in v4.0'),
    sa.Column('messages_sent_count', sa.Integer(), nullable=False, server_default='0', comment='Count of outbound messages sent by this agent'),
    sa.Column('messages_waiting_count', sa.Integer(), nullable=False, server_default='0', comment='Count of inbound messages waiting to be read'),
    sa.Column('messages_read_count', sa.Integer(), nullable=False, server_default='0', comment='Count of inbound messages that have been acknowledged/read'),
    sa.Column('failure_reason', sa.String(length=50), nullable=True, comment='Reason for failure: error, timeout, system_error (Handover 0113)'),
    sa.Column('agent_name', sa.String(length=255), nullable=True, comment='Human-readable display name for UI'),
    sa.CheckConstraint("health_status IN ('unknown', 'healthy', 'warning', 'critical', 'timeout')", name='ck_agent_execution_health_status'),
    sa.CheckConstraint("status IN ('waiting', 'working', 'blocked', 'complete', 'failed', 'cancelled', 'decommissioned')", name='ck_agent_execution_status'),
    sa.CheckConstraint("tool_type IN ('claude-code', 'codex', 'gemini', 'universal')", name='ck_agent_execution_tool_type'),
    sa.CheckConstraint('context_used >= 0 AND context_used <= context_budget', name='ck_agent_execution_context_usage'),
    sa.CheckConstraint('instance_number >= 1', name='ck_agent_execution_instance_positive'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_agent_execution_progress_range'),
    sa.ForeignKeyConstraint(['job_id'], ['agent_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index('idx_agent_executions_health', 'agent_executions', ['health_status'], unique=False)
    op.create_index('idx_agent_executions_instance', 'agent_executions', ['job_id', 'instance_number'], unique=False)
    op.create_index('idx_agent_executions_job', 'agent_executions', ['job_id'], unique=False)
    op.create_index('idx_agent_executions_last_progress', 'agent_executions', ['last_progress_at'], unique=False)
    op.create_index('idx_agent_executions_status', 'agent_executions', ['status'], unique=False)
    op.create_index('idx_agent_executions_tenant', 'agent_executions', ['tenant_key'], unique=False)
    op.create_index('idx_agent_executions_tenant_job', 'agent_executions', ['tenant_key', 'job_id'], unique=False)
    # Removed duplicate ix_agent_executions_job_id (same as idx_agent_executions_job)
    # Removed duplicate ix_agent_executions_tenant_key (same as idx_agent_executions_tenant)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('parent_task_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('converted_to_project_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('estimated_effort', sa.Float(), nullable=True),
    sa.Column('actual_effort', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['mcp_agent_jobs.job_id'], name='fk_task_job'),
    sa.ForeignKeyConstraint(['converted_to_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_job', 'tasks', ['job_id'], unique=False)
    op.create_index('idx_task_converted_to_project', 'tasks', ['converted_to_project_id'], unique=False)
    op.create_index('idx_task_created_by_user', 'tasks', ['created_by_user_id'], unique=False)
    op.create_index('idx_task_priority', 'tasks', ['priority'], unique=False)
    op.create_index('idx_task_product', 'tasks', ['product_id'], unique=False)
    op.create_index('idx_task_project', 'tasks', ['project_id'], unique=False)
    op.create_index('idx_task_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_task_tenant', 'tasks', ['tenant_key'], unique=False)
    op.create_index('idx_task_tenant_job', 'tasks', ['tenant_key', 'job_id'], unique=False)
    op.create_index('idx_task_tenant_created_user', 'tasks', ['tenant_key', 'created_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_tenant_created_user', table_name='tasks')
    op.drop_index('idx_task_tenant_job', table_name='tasks')
    op.drop_index('idx_task_tenant', table_name='tasks')
    op.drop_index('idx_task_status', table_name='tasks')
    op.drop_index('idx_task_project', table_name='tasks')
    op.drop_index('idx_task_product', table_name='tasks')
    op.drop_index('idx_task_priority', table_name='tasks')
    op.drop_index('idx_task_created_by_user', table_name='tasks')
    op.drop_index('idx_task_converted_to_project', table_name='tasks')
    op.drop_index('idx_task_job', table_name='tasks')
    op.drop_table('tasks')
    # Removed: op.drop_index(op.f('ix_agent_executions_tenant_key'), table_name='agent_executions')
    # Removed: op.drop_index(op.f('ix_agent_executions_job_id'), table_name='agent_executions')
    op.drop_index('idx_agent_executions_tenant_job', table_name='agent_executions')
    op.drop_index('idx_agent_executions_tenant', table_name='agent_executions')
    op.drop_index('idx_agent_executions_status', table_name='agent_executions')
    op.drop_index('idx_agent_executions_last_progress', table_name='agent_executions')
    op.drop_index('idx_agent_executions_job', table_name='agent_executions')
    op.drop_index('idx_agent_executions_instance', table_name='agent_executions')
    op.drop_index('idx_agent_executions_health', table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index('idx_vision_tenant', table_name='visions')
    op.drop_index('idx_vision_project', table_name='visions')
    op.drop_index('idx_vision_document', table_name='visions')
    op.drop_table('visions')
    op.drop_index('idx_usage_tenant', table_name='template_usage_stats')
    op.drop_index('idx_usage_template', table_name='template_usage_stats')
    op.drop_index('idx_usage_project', table_name='template_usage_stats')
    op.drop_index('idx_usage_date', table_name='template_usage_stats')
    op.drop_table('template_usage_stats')
    # NOTE: sessions table drops REMOVED (Handover 0423 - dead code cleanup)
    op.drop_index('idx_message_tenant', table_name='messages')
    op.drop_index('idx_message_status', table_name='messages')
    op.drop_index('idx_message_project', table_name='messages')
    op.drop_index('idx_message_priority', table_name='messages')
    op.drop_index('idx_message_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_mcp_sessions_tenant_key'), table_name='mcp_sessions')
    op.drop_index(op.f('ix_mcp_sessions_session_id'), table_name='mcp_sessions')
    op.drop_index('idx_mcp_session_tenant', table_name='mcp_sessions')
    op.drop_index('idx_mcp_session_last_accessed', table_name='mcp_sessions')
    op.drop_index('idx_mcp_session_expires', table_name='mcp_sessions')
    op.drop_index('idx_mcp_session_data_gin', table_name='mcp_sessions', postgresql_using='gin')
    op.drop_index('idx_mcp_session_cleanup', table_name='mcp_sessions')
    op.drop_index('idx_mcp_session_api_key', table_name='mcp_sessions')
    op.drop_table('mcp_sessions')
    op.drop_index(op.f('ix_mcp_context_index_tenant_key'), table_name='mcp_context_index')
    op.drop_index('idx_mcp_context_vision_doc', table_name='mcp_context_index')
    op.drop_index('idx_mcp_context_tenant_product', table_name='mcp_context_index')
    op.drop_index('idx_mcp_context_searchable', table_name='mcp_context_index', postgresql_using='gin')
    op.drop_index('idx_mcp_context_product_vision_doc', table_name='mcp_context_index')
    op.drop_index('idx_mcp_context_chunk_id', table_name='mcp_context_index')
    op.drop_table('mcp_context_index')
    op.drop_index(op.f('ix_mcp_agent_jobs_tenant_key'), table_name='mcp_agent_jobs')
    op.drop_index(op.f('ix_mcp_agent_jobs_project_id'), table_name='mcp_agent_jobs')
    op.drop_index('idx_mcp_agent_jobs_tenant_type', table_name='mcp_agent_jobs')
    op.drop_index('idx_mcp_agent_jobs_tenant_tool', table_name='mcp_agent_jobs')
    op.drop_index('idx_mcp_agent_jobs_tenant_status', table_name='mcp_agent_jobs')
    op.drop_index('idx_mcp_agent_jobs_tenant_project', table_name='mcp_agent_jobs')
    op.drop_index('idx_mcp_agent_jobs_project', table_name='mcp_agent_jobs')
    op.drop_index('idx_mcp_agent_jobs_last_progress', table_name='mcp_agent_jobs')
    op.drop_index('idx_mcp_agent_jobs_job_id', table_name='mcp_agent_jobs')
    op.drop_index('idx_mcp_agent_jobs_health_status', table_name='mcp_agent_jobs')
    op.drop_index('idx_mcp_agent_jobs_composite_status', table_name='mcp_agent_jobs')
    op.drop_index('idx_agent_jobs_instance', table_name='mcp_agent_jobs')
    op.drop_index('idx_agent_jobs_handover', table_name='mcp_agent_jobs')
    op.drop_table('mcp_agent_jobs')
    op.drop_index('idx_large_doc_tenant', table_name='large_document_index')
    op.drop_table('large_document_index')
    op.drop_index('idx_git_commit_trigger', table_name='git_commits')
    op.drop_index('idx_git_commit_tenant', table_name='git_commits')
    op.drop_index('idx_git_commit_project', table_name='git_commits')
    op.drop_index('idx_git_commit_product', table_name='git_commits')
    op.drop_index('idx_git_commit_hash', table_name='git_commits')
    op.drop_index('idx_git_commit_date', table_name='git_commits')
    op.drop_table('git_commits')
    op.drop_index('idx_discovery_tenant', table_name='discovery_config')
    op.drop_index('idx_discovery_project', table_name='discovery_config')
    op.drop_table('discovery_config')
    op.drop_index('idx_context_type', table_name='context_index')
    op.drop_index('idx_context_tenant', table_name='context_index')
    op.drop_index('idx_context_doc', table_name='context_index')
    op.drop_table('context_index')
    op.drop_index('idx_config_tenant', table_name='configurations')
    op.drop_index('idx_config_category', table_name='configurations')
    op.drop_table('configurations')
    # Removed: op.drop_index(op.f('ix_agent_jobs_tenant_key'), table_name='agent_jobs')
    # Removed: op.drop_index(op.f('ix_agent_jobs_project_id'), table_name='agent_jobs')
    op.drop_index('idx_agent_jobs_tenant_project', table_name='agent_jobs')
    op.drop_index('idx_agent_jobs_tenant', table_name='agent_jobs')
    op.drop_index('idx_agent_jobs_status', table_name='agent_jobs')
    op.drop_index('idx_agent_jobs_project', table_name='agent_jobs')
    op.drop_table('agent_jobs')
    op.drop_index('idx_interaction_type', table_name='agent_interactions')
    op.drop_index('idx_interaction_tenant', table_name='agent_interactions')
    op.drop_index('idx_interaction_project', table_name='agent_interactions')
    op.drop_index('idx_interaction_created', table_name='agent_interactions')
    op.drop_table('agent_interactions')
    op.drop_index(op.f('ix_vision_documents_tenant_key'), table_name='vision_documents')
    op.drop_index('idx_vision_doc_type', table_name='vision_documents')
    op.drop_index('idx_vision_doc_tenant_product', table_name='vision_documents')
    op.drop_index('idx_vision_doc_tenant', table_name='vision_documents')
    op.drop_index('idx_vision_doc_product_type', table_name='vision_documents')
    op.drop_index('idx_vision_doc_product_active', table_name='vision_documents')
    op.drop_index('idx_vision_doc_product', table_name='vision_documents')
    op.drop_index('idx_vision_doc_chunked', table_name='vision_documents')
    op.drop_index('idx_vision_doc_active', table_name='vision_documents')
    op.drop_table('vision_documents')
    # NOTE: template_augmentations table drops REMOVED (Handover 0423 - dead code cleanup)
    op.drop_index('idx_archive_version', table_name='template_archives')
    op.drop_index('idx_archive_tenant', table_name='template_archives')
    op.drop_index('idx_archive_template', table_name='template_archives')
    op.drop_index('idx_archive_product', table_name='template_archives')
    op.drop_index('idx_archive_date', table_name='template_archives')
    op.drop_table('template_archives')
    op.drop_index(op.f('ix_projects_alias'), table_name='projects')
    op.drop_index('idx_projects_deleted_at', table_name='projects', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('idx_projects_closeout_executed', table_name='projects', postgresql_where=sa.text('closeout_executed_at IS NOT NULL'))
    op.drop_index('idx_project_tenant', table_name='projects')
    op.drop_index('idx_project_status', table_name='projects')
    op.drop_index('idx_project_single_active_per_product', table_name='projects', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('projects')
    op.drop_index(op.f('ix_mcp_context_summary_tenant_key'), table_name='mcp_context_summary')
    op.drop_index('idx_mcp_summary_tenant_product', table_name='mcp_context_summary')
    op.drop_index('idx_mcp_summary_context_id', table_name='mcp_context_summary')
    op.drop_table('mcp_context_summary')
    op.drop_index(op.f('ix_api_keys_tenant_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index('idx_apikey_user', table_name='api_keys')
    op.drop_index('idx_apikey_tenant', table_name='api_keys')
    op.drop_index('idx_apikey_permissions_gin', table_name='api_keys', postgresql_using='gin')
    op.drop_index('idx_apikey_hash', table_name='api_keys')
    op.drop_index('idx_apikey_active', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_key'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_tenant', table_name='users')
    op.drop_index('idx_user_system', table_name='users')
    op.drop_index('idx_user_pin_lockout', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_setup_state_tenant_key'), table_name='setup_state')
    op.drop_index(op.f('ix_setup_state_first_admin_created'), table_name='setup_state')
    op.drop_index(op.f('ix_setup_state_database_initialized'), table_name='setup_state')
    op.drop_index('idx_setup_tools_gin', table_name='setup_state', postgresql_using='gin')
    op.drop_index('idx_setup_tenant', table_name='setup_state')
    op.drop_index('idx_setup_mode', table_name='setup_state')
    op.drop_index('idx_setup_fresh_install', table_name='setup_state', postgresql_where='first_admin_created = false')
    op.drop_index('idx_setup_features_gin', table_name='setup_state', postgresql_using='gin')
    op.drop_index('idx_setup_database_initialized', table_name='setup_state')
    op.drop_index('idx_setup_database_incomplete', table_name='setup_state', postgresql_where='database_initialized = false')
    op.drop_table('setup_state')
    op.drop_index(op.f('ix_settings_tenant_key'), table_name='settings')
    op.drop_index('idx_settings_tenant', table_name='settings')
    op.drop_index('idx_settings_category', table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_products_tenant_key'), table_name='products')
    op.drop_index('idx_products_deleted_at', table_name='products', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('idx_product_tenant', table_name='products')
    op.drop_index('idx_product_single_active_per_tenant', table_name='products', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_product_name', table_name='products')
    op.drop_index('idx_product_memory_gin', table_name='products', postgresql_using='gin')
    op.drop_index('idx_product_config_data_gin', table_name='products', postgresql_using='gin')
    op.drop_table('products')
    op.drop_index(op.f('ix_optimization_rules_tenant_key'), table_name='optimization_rules')
    op.drop_index('idx_optimization_rule_type', table_name='optimization_rules')
    op.drop_index('idx_optimization_rule_tenant', table_name='optimization_rules')
    op.drop_index('idx_optimization_rule_active', table_name='optimization_rules')
    op.drop_table('optimization_rules')
    op.drop_index(op.f('ix_optimization_metrics_tenant_key'), table_name='optimization_metrics')
    op.drop_index('idx_optimization_metric_type', table_name='optimization_metrics')
    op.drop_index('idx_optimization_metric_tenant', table_name='optimization_metrics')
    op.drop_index('idx_optimization_metric_optimized', table_name='optimization_metrics')
    op.drop_index('idx_optimization_metric_date', table_name='optimization_metrics')
    op.drop_table('optimization_metrics')
    op.drop_index('idx_job_tenant', table_name='jobs')
    op.drop_index('idx_job_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_git_config_tenant', table_name='git_configs')
    op.drop_index('idx_git_config_product', table_name='git_configs')
    op.drop_index('idx_git_config_auth', table_name='git_configs')
    op.drop_index('idx_git_config_active', table_name='git_configs')
    op.drop_table('git_configs')
    op.drop_index(op.f('ix_download_tokens_token'), table_name='download_tokens')
    op.drop_index(op.f('ix_download_tokens_tenant_key'), table_name='download_tokens')
    op.drop_index('idx_download_token_token', table_name='download_tokens')
    op.drop_index('idx_download_token_tenant_type', table_name='download_tokens')
    op.drop_index('idx_download_token_tenant', table_name='download_tokens')
    op.drop_index('idx_download_token_expires', table_name='download_tokens')
    op.drop_table('download_tokens')
    op.drop_index(op.f('ix_api_metrics_tenant_key'), table_name='api_metrics')
    op.drop_index('idx_api_metrics_tenant_date', table_name='api_metrics')
    op.drop_table('api_metrics')
    # Removed: op.drop_index(op.f('ix_agent_templates_tool'), table_name='agent_templates')
    op.drop_index('idx_template_tool', table_name='agent_templates')
    op.drop_index('idx_template_tenant', table_name='agent_templates')
    op.drop_index('idx_template_role', table_name='agent_templates')
    op.drop_index('idx_template_product', table_name='agent_templates')
    op.drop_index('idx_template_category', table_name='agent_templates')
    op.drop_index('idx_template_active', table_name='agent_templates')
    op.drop_table('agent_templates')
    # ### end Alembic commands ###
