"""add_quality_standards_to_product

Revision ID: 583c4b97e1ae
Revises: f4121f77a2d9
Create Date: 2025-11-18 01:48:11.648129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583c4b97e1ae'
down_revision: Union[str, Sequence[str], None] = 'f4121f77a2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_context_summary', 'reduction_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Context prioritization percentage achieved',
               existing_comment='Token reduction percentage achieved',
               existing_nullable=True)
    op.add_column('products', sa.Column('quality_standards', sa.Text(), nullable=True, comment='Quality standards and testing expectations'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quality_standards')
    op.alter_column('mcp_context_summary', 'reduction_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Token reduction percentage achieved',
               existing_comment='Context prioritization percentage achieved',
               existing_nullable=True)
    # ### end Alembic commands ###
