"""add_last_exported_at_to_agent_templates_handover_0335

Revision ID: 7983bf9c91c9
Revises: ad91f3ce8c9b
Create Date: 2025-12-08 19:55:20.768980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7983bf9c91c9'
down_revision: Union[str, Sequence[str], None] = 'ad91f3ce8c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted for idempotency ###
    conn = op.get_bind()

    # Handover 0335: Add last_exported_at column for template staleness tracking
    conn.execute(sa.text(
        "ALTER TABLE agent_templates ADD COLUMN IF NOT EXISTS last_exported_at TIMESTAMP WITH TIME ZONE"
    ))

    # Add mission_acknowledged_at if it doesn't exist (missing from baseline)
    conn.execute(sa.text(
        "ALTER TABLE mcp_agent_jobs ADD COLUMN IF NOT EXISTS mission_acknowledged_at TIMESTAMP WITH TIME ZONE"
    ))

    # Add comment to mission_acknowledged_at
    conn.execute(sa.text(
        "COMMENT ON COLUMN mcp_agent_jobs.mission_acknowledged_at IS "
        "'Timestamp when agent first fetched mission via get_agent_mission() or get_orchestrator_instructions()'"
    ))

    # Create indexes if they don't exist (using raw SQL for idempotency)
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_mcp_agent_jobs_composite_status ON mcp_agent_jobs (project_id, status, last_progress_at)"
    ))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_mcp_agent_jobs_health_status ON mcp_agent_jobs (health_status)"
    ))
    conn.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_mcp_agent_jobs_last_progress ON mcp_agent_jobs (last_progress_at)"
    ))

    # Add messages.result column if it doesn't exist (missing from baseline)
    conn.execute(sa.text(
        "ALTER TABLE messages ADD COLUMN IF NOT EXISTS result TEXT"
    ))

    # Add comments to columns (idempotent - overwrites existing comments)
    conn.execute(sa.text(
        "COMMENT ON COLUMN products.product_memory IS "
        "'360 Memory: GitHub integration, sequential history, context summaries (Handover 0135)'"
    ))
    conn.execute(sa.text(
        "COMMENT ON COLUMN projects.execution_mode IS "
        "'Execution mode: multi_terminal (manual) or claude_code_cli (single terminal with Task tool)'"
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted for idempotency ###
    conn = op.get_bind()

    # Remove comments (set to NULL)
    conn.execute(sa.text("COMMENT ON COLUMN projects.execution_mode IS NULL"))
    conn.execute(sa.text("COMMENT ON COLUMN products.product_memory IS NULL"))
    conn.execute(sa.text("COMMENT ON COLUMN mcp_agent_jobs.mission_acknowledged_at IS NULL"))

    # Drop indexes if they exist
    conn.execute(sa.text("DROP INDEX IF EXISTS idx_mcp_agent_jobs_last_progress"))
    conn.execute(sa.text("DROP INDEX IF EXISTS idx_mcp_agent_jobs_health_status"))
    conn.execute(sa.text("DROP INDEX IF EXISTS idx_mcp_agent_jobs_composite_status"))

    # Drop columns added by this migration (if they exist)
    conn.execute(sa.text("ALTER TABLE messages DROP COLUMN IF EXISTS result"))
    conn.execute(sa.text("ALTER TABLE mcp_agent_jobs DROP COLUMN IF EXISTS mission_acknowledged_at"))
    conn.execute(sa.text("ALTER TABLE agent_templates DROP COLUMN IF EXISTS last_exported_at"))
    # ### end Alembic commands ###
