# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the GiljoAI Community License v1.1.
# See LICENSE in the project root for terms.
# [CE] Community Edition — source-available, single-user use only.

"""
Project and session-related models for GiljoAI MCP.

This module contains models for projects, project types, and development sessions.
Projects are work initiatives that belong to products. Project types define
taxonomy categories (e.g., Backend, Frontend, API) for structured project naming.
"""

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from .base import Base, generate_project_alias, generate_uuid


class ProjectType(Base):
    """
    Project type model - taxonomy categories for structured project naming.

    Each project type defines an abbreviation (e.g., "BE" for Backend, "FE" for Frontend)
    that is used to generate taxonomy aliases like BE-0001, FE-0002a.

    Handover 0440a: Initial implementation for project taxonomy system.
    """

    __tablename__ = "project_types"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    tenant_key = Column(String(36), nullable=False, index=True)
    abbreviation = Column(
        String(4),
        nullable=False,
        comment="2-4 uppercase letter abbreviation (e.g., BE, FE, API)",
    )
    label = Column(String(50), nullable=False, comment="Human-readable label (e.g., Backend, Frontend)")
    color = Column(String(7), nullable=False, default="#607D8B", comment="Hex color for UI display")
    sort_order = Column(Integer, default=0, comment="Display ordering in UI dropdowns")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    projects = relationship("Project", back_populates="project_type")

    __table_args__ = (
        UniqueConstraint("tenant_key", "abbreviation", name="uq_project_type_abbr"),
        Index("idx_project_type_tenant", "tenant_key"),
    )

    def __repr__(self) -> str:
        return f"<ProjectType(id={self.id}, abbreviation='{self.abbreviation}', label='{self.label}')>"


class Project(Base):
    """
    Project model - work initiatives with vision documents.
    Projects belong to a Product and can be created from Tasks.

    Handover 0073: Enhanced with orchestrator closeout support for project completion tracking.
    Handover 0440a: Added taxonomy fields (project_type_id, series_number, subseries).
    """

    __tablename__ = "projects"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    tenant_key = Column(String(36), nullable=False, default=generate_uuid)
    product_id = Column(
        String(36), ForeignKey("products.id", ondelete="CASCADE"), nullable=True
    )  # Projects belong to Products
    name = Column(String(255), nullable=False)
    alias = Column(
        String(6),
        nullable=False,
        unique=True,
        index=True,
        default=generate_project_alias,
        comment="6-character alphanumeric project identifier (e.g., A1B2C3)",
    )

    # Human-written project description (Handover 0062)
    description = Column(Text, nullable=False)

    # Mission statement (AI-generated by orchestrator)
    mission = Column(Text, nullable=False)
    status = Column(
        String(50), default="inactive"
    )  # inactive, active, completed, cancelled, deleted (Handover 0071: removed paused/archived)

    # Handover 0108: Staging workflow status tracking
    staging_status = Column(
        String(50),
        nullable=True,
        comment="Staging workflow status: null (not staged), staging (in progress), or staging_complete",
    )

    # Handover 0440a: Project taxonomy fields
    project_type_id = Column(
        String(36),
        ForeignKey("project_types.id", ondelete="SET NULL"),
        nullable=True,
        comment="FK to project_types for taxonomy classification",
    )
    series_number = Column(
        Integer,
        nullable=True,
        comment="Sequential number within a project type (e.g., 1 in BE-0001)",
    )
    subseries = Column(
        String(1),
        nullable=True,
        comment="Single-letter subseries suffix (e.g., 'a' in BE-0001a)",
    )

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)
    activated_at = Column(
        DateTime(timezone=True), nullable=True, comment="First activation timestamp (only set once on first activation)"
    )
    implementation_launched_at = Column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when user clicked Implement button. NULL = staging only.",
    )
    paused_at = Column(
        DateTime(timezone=True), nullable=True, comment="Timestamp when project was last paused/deactivated"
    )
    deleted_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when project was soft deleted (NULL for active projects)",
    )
    cancellation_reason = Column(Text, nullable=True, comment="Reason for project cancellation")
    deactivation_reason = Column(Text, nullable=True, comment="Reason for project deactivation")
    early_termination = Column(
        Boolean,
        nullable=True,
        default=False,
        server_default=text("false"),
        comment="Whether project was terminated early via termination prompt",
    )

    # Handover 0073: Orchestrator closeout support
    orchestrator_summary = Column(
        Text, nullable=True, comment="AI-generated final summary of project outcomes and deliverables"
    )
    closeout_prompt = Column(
        Text, nullable=True, comment="Prompt template used by orchestrator for closeout generation"
    )
    closeout_executed_at = Column(
        DateTime(timezone=True), nullable=True, comment="Timestamp when closeout workflow was executed"
    )
    closeout_checklist = Column(
        JSONB,
        default=list,
        nullable=False,
        server_default=text("'[]'::jsonb"),
        comment="Structured checklist of closeout tasks (JSONB array)",
    )

    # Handover 0260: Execution mode for Claude Code CLI toggle persistence
    execution_mode = Column(
        String(20),
        nullable=False,
        default="multi_terminal",
        server_default=text("'multi_terminal'"),
        comment="Execution mode: 'multi_terminal' (manual) or 'claude_code_cli' (single terminal with Task tool)",
    )

    # Handover 0904: Orchestrator auto check-in settings (multi-terminal only)
    auto_checkin_enabled = Column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="Enable orchestrator self-polling in multi-terminal mode",
    )
    auto_checkin_interval = Column(
        Integer,
        nullable=False,
        default=10,
        server_default=text("10"),
        comment="Auto check-in interval in minutes (5, 10, 15, 20, 30, 40, 60)",
    )

    # Relationships
    product = relationship("Product", back_populates="projects")
    project_type = relationship("ProjectType", back_populates="projects")
    agent_jobs_v2 = relationship("AgentJob", back_populates="project", cascade="all, delete-orphan")  # Handover 0366a
    messages = relationship("Message", back_populates="project", cascade="all, delete-orphan")
    tasks = relationship(
        "Task", foreign_keys="Task.project_id", back_populates="project", cascade="all, delete-orphan"
    )  # Specify FK to avoid ambiguity
    memory_entries = relationship("ProductMemoryEntry", back_populates="project")  # Handover 0390a

    __table_args__ = (
        # Partial unique index: only enforces uniqueness on active (non-deleted) rows.
        # Allows re-use of taxonomy combinations after soft-deleting a project.
        Index(
            "uq_project_taxonomy_active",
            "tenant_key",
            "project_type_id",
            "series_number",
            "subseries",
            unique=True,
            postgresql_where=text("deleted_at IS NULL"),
        ),
        Index("idx_project_tenant", "tenant_key"),
        Index("idx_project_status", "status"),
        # Handover 0070: Soft delete support
        Index("idx_projects_deleted_at", "deleted_at", postgresql_where=text("deleted_at IS NOT NULL")),
        # Handover 0073: Closeout support
        Index(
            "idx_projects_closeout_executed",
            "closeout_executed_at",
            postgresql_where=text("closeout_executed_at IS NOT NULL"),
        ),
        # Single active project per product constraint (Handover 0050b)
        # Ensures only ONE project can be active per product at any time
        Index(
            "idx_project_single_active_per_product",
            "product_id",
            unique=True,
            postgresql_where=text("status = 'active'"),
        ),
    )

    @property
    def taxonomy_alias(self) -> str:
        """Generate a structured taxonomy alias from independent fields.

        Supports any combination: type-only ("BE"), serial-only ("0042"),
        type+serial ("BE-0042"), or full ("BE-0042a").
        Falls back to the random 6-char alias if no taxonomy fields are set.
        """
        parts = []
        if self.project_type_id and self.project_type:
            parts.append(self.project_type.abbreviation)
        if self.series_number:
            if parts:
                parts.append("-")
            parts.append(f"{self.series_number:04d}")
            if self.subseries:
                parts.append(self.subseries)
        return "".join(parts) if parts else self.alias

    def __repr__(self) -> str:
        return f"<Project(id={self.id}, name='{self.name}', product_id='{self.product_id}')>"
