"""
Project and session-related models for GiljoAI MCP.

This module contains models for projects and development sessions.
Projects are work initiatives that belong to products.
"""

from sqlalchemy import (
    JSON,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from .base import Base, generate_project_alias, generate_uuid


class Project(Base):
    """
    Project model - work initiatives with vision documents.
    Projects belong to a Product and can be created from Tasks.

    Handover 0073: Enhanced with orchestrator closeout support for project completion tracking.
    """

    __tablename__ = "projects"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    tenant_key = Column(String(36), nullable=False, default=generate_uuid)
    product_id = Column(
        String(36), ForeignKey("products.id", ondelete="CASCADE"), nullable=True
    )  # Projects belong to Products
    name = Column(String(255), nullable=False)
    alias = Column(
        String(6),
        nullable=False,
        unique=True,
        index=True,
        default=generate_project_alias,
        comment="6-character alphanumeric project identifier (e.g., A1B2C3)",
    )

    # Human-written project description (Handover 0062)
    description = Column(Text, nullable=False)

    # Mission statement (AI-generated by orchestrator)
    mission = Column(Text, nullable=False)
    status = Column(
        String(50), default="inactive"
    )  # inactive, active, completed, cancelled, deleted (Handover 0071: removed paused/archived)

    # Handover 0108: Staging workflow status tracking
    staging_status = Column(
        String(50),
        nullable=True,
        comment="Staging workflow status: null, staging, staged, cancelled, launching, active",
    )

    context_used = Column(Integer, default=0)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)
    activated_at = Column(
        DateTime(timezone=True), nullable=True, comment="First activation timestamp (only set once on first activation)"
    )
    implementation_launched_at = Column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when user clicked Implement button. NULL = staging only.",
    )
    paused_at = Column(
        DateTime(timezone=True), nullable=True, comment="Timestamp when project was last paused/deactivated"
    )
    deleted_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when project was soft deleted (NULL for active projects)",
    )
    meta_data = Column(JSON, default=dict)

    # Handover 0073: Orchestrator closeout support
    orchestrator_summary = Column(
        Text, nullable=True, comment="AI-generated final summary of project outcomes and deliverables"
    )
    closeout_prompt = Column(
        Text, nullable=True, comment="Prompt template used by orchestrator for closeout generation"
    )
    closeout_executed_at = Column(
        DateTime(timezone=True), nullable=True, comment="Timestamp when closeout workflow was executed"
    )
    closeout_checklist = Column(
        JSONB,
        default=list,
        nullable=False,
        server_default=text("'[]'::jsonb"),
        comment="Structured checklist of closeout tasks (JSONB array)",
    )

    # Handover 0260: Execution mode for Claude Code CLI toggle persistence
    execution_mode = Column(
        String(20),
        nullable=False,
        default="multi_terminal",
        server_default=text("'multi_terminal'"),
        comment="Execution mode: 'multi_terminal' (manual) or 'claude_code_cli' (single terminal with Task tool)",
    )

    # Relationships
    product = relationship("Product", back_populates="projects")
    agent_jobs_v2 = relationship("AgentJob", back_populates="project", cascade="all, delete-orphan")  # Handover 0366a
    messages = relationship("Message", back_populates="project", cascade="all, delete-orphan")
    tasks = relationship(
        "Task", foreign_keys="Task.project_id", back_populates="project", cascade="all, delete-orphan"
    )  # Specify FK to avoid ambiguity
    context_indexes = relationship("ContextIndex", back_populates="project", cascade="all, delete-orphan")
    document_indexes = relationship("LargeDocumentIndex", back_populates="project", cascade="all, delete-orphan")
    memory_entries = relationship("ProductMemoryEntry", back_populates="project")  # Handover 0390a

    __table_args__ = (
        Index("idx_project_tenant", "tenant_key"),
        Index("idx_project_status", "status"),
        # Handover 0070: Soft delete support
        Index("idx_projects_deleted_at", "deleted_at", postgresql_where=text("deleted_at IS NOT NULL")),
        # Handover 0073: Closeout support
        Index(
            "idx_projects_closeout_executed",
            "closeout_executed_at",
            postgresql_where=text("closeout_executed_at IS NOT NULL"),
        ),
        # Single active project per product constraint (Handover 0050b)
        # Ensures only ONE project can be active per product at any time
        Index(
            "idx_project_single_active_per_product",
            "product_id",
            unique=True,
            postgresql_where=text("status = 'active'"),
        ),
    )

    def __repr__(self) -> str:
        return f"<Project(id={self.id}, name='{self.name}', product_id='{self.product_id}')>"
