# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the Elastic License 2.0.
# See LICENSE in the project root for terms.
# [CE] Community Edition.

"""
Project and session-related models for GiljoAI MCP.

This module contains models for projects and taxonomy types. Projects are work
initiatives that belong to products. Taxonomy types define classification
categories (e.g., Backend, Frontend, API) shared by projects (for structured
naming like BE-0001) and tasks.
"""

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    and_,
    case,
    literal,
    select,
    text,
)
from sqlalchemy import (
    Enum as SQLAlchemyEnum,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import column_property, relationship
from sqlalchemy.sql import func

from giljo_mcp.domain.project_status import ProjectStatus

from .base import Base, generate_project_alias, generate_uuid


class TaxonomyType(Base):
    """
    Taxonomy type model - unified taxonomy categories for projects and tasks.

    Each taxonomy type defines an abbreviation (e.g., "BE" for Backend, "FE" for Frontend)
    used to generate project taxonomy aliases (BE-0001, FE-0002a) and to classify tasks.

    Handover 0440a: Initial implementation for project taxonomy system (as ProjectType).
    Phase A (agent-parity, 2026-05): Renamed to TaxonomyType to reflect that the same
    classification table now serves both projects and tasks. Table renamed
    project_types -> taxonomy_types in migration ce_0014.
    """

    __tablename__ = "taxonomy_types"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    tenant_key = Column(String(36), nullable=False, index=True)
    abbreviation = Column(
        String(4),
        nullable=False,
        comment="2-4 uppercase letter abbreviation (e.g., BE, FE, API)",
    )
    label = Column(String(50), nullable=False, comment="Human-readable label (e.g., Backend, Frontend)")
    color = Column(String(7), nullable=False, default="#607D8B", comment="Hex color for UI display")
    sort_order = Column(Integer, default=0, comment="Display ordering in UI dropdowns")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    projects = relationship("Project", back_populates="project_type")

    __table_args__ = (
        UniqueConstraint("tenant_key", "abbreviation", name="uq_taxonomy_type_abbr"),
        Index("idx_taxonomy_type_tenant", "tenant_key"),
    )

    def __repr__(self) -> str:
        return f"<TaxonomyType(id={self.id}, abbreviation='{self.abbreviation}', label='{self.label}')>"


class Project(Base):
    """
    Project model - work initiatives with vision documents.
    Projects belong to a Product and can be created from Tasks.

    Handover 0073: Enhanced with orchestrator closeout support for project completion tracking.
    Handover 0440a: Added taxonomy fields (project_type_id, series_number, subseries).
    """

    __tablename__ = "projects"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    tenant_key = Column(String(36), nullable=False, default=generate_uuid)
    product_id = Column(
        String(36), ForeignKey("products.id", ondelete="CASCADE"), nullable=True
    )  # Projects belong to Products
    name = Column(String(255), nullable=False)
    alias = Column(
        String(6),
        nullable=False,
        unique=True,
        index=True,
        default=generate_project_alias,
        comment="6-character alphanumeric project identifier (e.g., A1B2C3)",
    )

    # Human-written project description (Handover 0062)
    description = Column(Text, nullable=False)

    # Mission statement (AI-generated by orchestrator)
    mission = Column(Text, nullable=False)
    # Project lifecycle status. Backed by the Postgres ENUM ``project_status``
    # created by migration ce_0008_project_status_enum (BE-5039 Phase 2a).
    # Canonical members: INACTIVE, ACTIVE, COMPLETED, CANCELLED, TERMINATED,
    # DELETED -- declared in giljo_mcp.domain.project_status.ProjectStatus.
    #
    # ``create_type=True`` (SQLAlchemy default) lets ``Base.metadata.create_all``
    # create the type when used in test setup -- the production CE chain
    # uses migration ``ce_0008_project_status_enum`` instead, which is
    # guarded by ``IF NOT EXISTS`` so the two paths cannot conflict.
    # ``values_callable`` writes the .value strings (not the member names)
    # to the DB; ``native_enum=True`` is the Postgres default.
    status = Column(
        SQLAlchemyEnum(
            ProjectStatus,
            name="project_status",
            native_enum=True,
            values_callable=lambda enum_cls: [m.value for m in enum_cls],
        ),
        nullable=False,
        default=ProjectStatus.INACTIVE,
        server_default=text("'inactive'::project_status"),
    )

    # Handover 0108: Staging workflow status tracking
    staging_status = Column(
        String(50),
        nullable=True,
        comment="Staging workflow status: null (not staged), staging (in progress), or staging_complete",
    )

    # Handover 0440a: Project taxonomy fields
    project_type_id = Column(
        String(36),
        ForeignKey("taxonomy_types.id", ondelete="SET NULL"),
        nullable=True,
        comment="FK to taxonomy_types for taxonomy classification",
    )
    series_number = Column(
        Integer,
        nullable=True,
        comment="Sequential number within a project type (e.g., 1 in BE-0001)",
    )
    subseries = Column(
        String(1),
        nullable=True,
        comment="Single-letter subseries suffix (e.g., 'a' in BE-0001a)",
    )

    # CE-OPT-4: UI visibility flag (hidden projects excluded from default list view)
    hidden = Column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="Whether project is hidden from default list view",
    )

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    completed_at = Column(DateTime(timezone=True), nullable=True)
    activated_at = Column(
        DateTime(timezone=True), nullable=True, comment="First activation timestamp (only set once on first activation)"
    )
    implementation_launched_at = Column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when user clicked Implement button. NULL = staging only.",
    )
    deleted_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when project was soft deleted (NULL for active projects)",
    )
    cancellation_reason = Column(Text, nullable=True, comment="Reason for project cancellation")
    deactivation_reason = Column(Text, nullable=True, comment="Reason for project deactivation")
    early_termination = Column(
        Boolean,
        nullable=True,
        default=False,
        server_default=text("false"),
        comment="Whether project was terminated early via termination prompt",
    )

    # Handover 0073: Orchestrator closeout support
    orchestrator_summary = Column(
        Text, nullable=True, comment="AI-generated final summary of project outcomes and deliverables"
    )
    closeout_prompt = Column(
        Text, nullable=True, comment="Prompt template used by orchestrator for closeout generation"
    )
    closeout_executed_at = Column(
        DateTime(timezone=True), nullable=True, comment="Timestamp when closeout workflow was executed"
    )
    closeout_checklist = Column(
        JSONB,
        default=list,
        nullable=False,
        server_default=text("'[]'::jsonb"),
        comment="Structured checklist of closeout tasks (JSONB array)",
    )

    # Handover 0260: Execution mode for Claude Code CLI toggle persistence
    execution_mode = Column(
        String(20),
        nullable=False,
        default="multi_terminal",
        server_default=text("'multi_terminal'"),
        comment="Execution mode: 'multi_terminal' (manual) or 'claude_code_cli' (single terminal with Task tool)",
    )

    # Handover 0904: Orchestrator auto check-in settings (multi-terminal only)
    auto_checkin_enabled = Column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="Enable orchestrator self-polling in multi-terminal mode",
    )
    auto_checkin_interval = Column(
        Integer,
        nullable=False,
        default=10,
        server_default=text("10"),
        comment="Auto check-in interval in minutes (5, 10, 15, 20, 30, 40, 60)",
    )

    # Relationships
    product = relationship("Product", back_populates="projects")
    project_type = relationship("TaxonomyType", back_populates="projects")
    agent_jobs_v2 = relationship("AgentJob", back_populates="project", cascade="all, delete-orphan")  # Handover 0366a
    messages = relationship("Message", back_populates="project", cascade="all, delete-orphan")
    tasks = relationship(
        "Task", foreign_keys="Task.project_id", back_populates="project", cascade="all, delete-orphan"
    )  # Specify FK to avoid ambiguity
    memory_entries = relationship("ProductMemoryEntry", back_populates="project")  # Handover 0390a

    __table_args__ = (
        # Partial unique index: only enforces uniqueness on active (non-deleted) rows.
        # Allows re-use of taxonomy combinations after soft-deleting a project.
        Index(
            "uq_project_taxonomy_active",
            "tenant_key",
            "product_id",
            "project_type_id",
            "series_number",
            "subseries",
            unique=True,
            postgresql_where=text("deleted_at IS NULL"),
        ),
        Index("idx_project_tenant", "tenant_key"),
        Index("idx_project_status", "status"),
        # Handover 0070: Soft delete support
        Index("idx_projects_deleted_at", "deleted_at", postgresql_where=text("deleted_at IS NOT NULL")),
        # Handover 0073: Closeout support
        Index(
            "idx_projects_closeout_executed",
            "closeout_executed_at",
            postgresql_where=text("closeout_executed_at IS NOT NULL"),
        ),
        # Single active project per product constraint (Handover 0050b)
        # Ensures only ONE project can be active per product at any time
        Index(
            "idx_project_single_active_per_product",
            "product_id",
            unique=True,
            postgresql_where=text("status = 'active'"),
        ),
    )

    def __repr__(self) -> str:
        return f"<Project(id={self.id}, name='{self.name}', product_id='{self.product_id}')>"


# BE-5058: ``taxonomy_alias`` is a SELECT-time correlated expression so sync
# consumers can read it on a project fetched without ``joinedload(project_type)``
# without triggering an async lazy load (the prior ``@property`` form crashed
# as MissingGreenlet from non-greenlet contexts). The correlated subquery is
# tenant-scoped to keep the model layer's defense-in-depth boundary intact.
_project_abbr_subq = (
    select(TaxonomyType.abbreviation)
    .where(
        TaxonomyType.id == Project.project_type_id,
        TaxonomyType.tenant_key == Project.tenant_key,
    )
    .correlate(Project)
    .scalar_subquery()
)

Project.taxonomy_alias = column_property(
    case(
        (
            and_(Project.project_type_id.is_(None), Project.series_number.is_(None)),
            Project.alias,
        ),
        (
            Project.series_number.is_(None),
            func.coalesce(_project_abbr_subq, literal("")),
        ),
        else_=(
            func.coalesce(_project_abbr_subq, literal(""))
            + case(
                (_project_abbr_subq.is_not(None), literal("-")),
                else_=literal(""),
            )
            + func.lpad(func.cast(Project.series_number, String), 4, literal("0"))
            + func.coalesce(Project.subseries, literal(""))
        ),
    ),
    deferred=False,
)
