# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the GiljoAI Community License v1.1.
# See LICENSE in the project root for terms.
# [CE] Community Edition — source-available, single-user use only.

"""
Security Headers Middleware

Adds production-grade security headers to all responses.

Created in Handover 0129c - Security Hardening & OWASP Compliance
Updated in Handover 1007 - Hash-Based CSP Implementation
"""

import logging
import os
from typing import Callable

from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware


logger = logging.getLogger(__name__)

# CSP hashes for inline code blocks in frontend/index.html
# Generated by scripts/generate_csp_hashes.py
# Regenerate if inline code changes
CSP_STYLE_HASH = "'sha256-Z2X8onHhSXt6iXyzdscOiXMXGyGcAkgrpqadNkU+Q54='"  # Loading animation styles
CSP_SCRIPT_HASH_1 = "'sha256-rrhdMJon1LlNs/ESh4RgEqLZSzXAOIoGHSuyl9MKq2o='"  # API URL configuration
CSP_SCRIPT_HASH_2 = "'sha256-9XkwnMC0DQdZQu3V1Q25B0kACYwZdGz6ajUA9yEYU4k='"  # Splash screen logic


def is_development_mode() -> bool:
    """
    Detect if running in development mode.

    Checks (in order):
    1. GILJO_ENV environment variable (dev/development)
    2. ENVIRONMENT environment variable (dev/development)
    3. Default to production (fail-safe)

    Returns:
        True if development mode, False for production
    """
    env = os.getenv("GILJO_ENV", "").lower()
    if env in ("dev", "development"):
        return True

    env = os.getenv("ENVIRONMENT", "").lower()
    # Return the condition directly
    return env in ("dev", "development")


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """
    Middleware to add security headers to all responses.

    Headers added:
    - Strict-Transport-Security (HSTS): Enforce HTTPS
    - Content-Security-Policy (CSP): Prevent XSS (hash-based, no unsafe-inline)
    - X-Frame-Options: Prevent clickjacking
    - X-Content-Type-Options: Prevent MIME sniffing
    - Referrer-Policy: Control referrer information
    - Permissions-Policy: Control browser features
    - X-XSS-Protection: Legacy XSS protection

    All headers follow OWASP security best practices.

    CSP Implementation (Handover 1007):
    - Uses SHA-256 hashes for inline scripts and styles
    - Production: No unsafe-inline or unsafe-eval
    - Development: Allows unsafe-eval for HMR (Hot Module Replacement)
    - Hashes are calculated from exact content in frontend/index.html
    """

    def __init__(self, app, hsts_max_age: int = 31536000):
        """
        Initialize security headers middleware.

        Args:
            app: FastAPI application instance
            hsts_max_age: HSTS max-age in seconds (default: 1 year)
        """
        super().__init__(app)
        self.hsts_max_age = hsts_max_age
        self.is_dev = is_development_mode()

        mode_str = "DEVELOPMENT" if self.is_dev else "PRODUCTION"
        logger.info(f"SecurityHeadersMiddleware initialized in {mode_str} mode")
        logger.info(f"HSTS max-age: {hsts_max_age}s")

        if self.is_dev:
            logger.warning("CSP: unsafe-eval enabled for development HMR")

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        """
        Add security headers to response.

        Args:
            request: Incoming HTTP request
            call_next: Next middleware/handler in chain

        Returns:
            Response with security headers added
        """
        response = await call_next(request)

        # HSTS: Only add for HTTPS connections (meaningless for HTTP)
        if request.url.scheme == "https":
            response.headers["Strict-Transport-Security"] = f"max-age={self.hsts_max_age}; includeSubDomains; preload"

        # CSP: Hash-based policy preventing XSS
        # Production: Strict hashes only
        # Development: Hashes + unsafe-eval for Vue HMR
        script_src = f"'self' {CSP_SCRIPT_HASH_1} {CSP_SCRIPT_HASH_2}"
        if self.is_dev:
            script_src += " 'unsafe-eval'"  # Vue HMR needs eval in dev

        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; "
            f"script-src {script_src}; "
            f"style-src 'self' 'unsafe-inline' {CSP_STYLE_HASH}; "
            "img-src 'self' data: https:; "
            "font-src 'self' data:; "
            "connect-src 'self' ws: wss:; "  # WebSocket connections
            "frame-ancestors 'none'; "  # No embedding
            "base-uri 'self'; "
            "form-action 'self'"
        )

        # X-Frame-Options: Prevent clickjacking
        response.headers["X-Frame-Options"] = "DENY"

        # X-Content-Type-Options: Prevent MIME sniffing
        response.headers["X-Content-Type-Options"] = "nosniff"

        # Referrer-Policy: Limit referrer information
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"

        # Permissions-Policy: Disable unnecessary features
        response.headers["Permissions-Policy"] = (
            "geolocation=(), "
            "microphone=(), "
            "camera=(), "
            "payment=(), "
            "usb=(), "
            "magnetometer=(), "
            "gyroscope=(), "
            "accelerometer=()"
        )

        # X-XSS-Protection: Legacy XSS protection (deprecated but harmless)
        response.headers["X-XSS-Protection"] = "1; mode=block"

        return response
