# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the GiljoAI Community License v1.1.
# See LICENSE in the project root for terms.
# [CE] Community Edition — source-available, single-user use only.

"""
Security Headers Middleware

Adds production-grade security headers to all responses.

Created in Handover 0129c - Security Hardening & OWASP Compliance
Updated in Handover 1007 - Hash-Based CSP Implementation
Updated: Dynamic CSP connect-src includes external_host when configured
"""

import logging
import os
from collections.abc import Callable

from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware


logger = logging.getLogger(__name__)

# CSP hashes for inline code blocks in frontend/index.html
# Generated by scripts/generate_csp_hashes.py
# Regenerate if inline code changes
CSP_STYLE_HASH = "'sha256-pR5eQD+pcfGctW0ZvPpp3UToUJkVDBclZbDZVJBZoBU='"  # Loading animation styles
CSP_SCRIPT_HASH_1 = "'sha256-r7V3kEf3vDjGGONDt5/ePMPMA3l3zGLcXje6KaTDS3U='"  # API URL configuration (INF-5012c)
CSP_SCRIPT_HASH_2 = "'sha256-T+y4FnL+BP2aiGWNs6H5HdyLosVMnGaNc9v+5DaNNJM='"  # Splash screen logic


def is_development_mode() -> bool:
    """
    Detect if running in development mode.

    Checks (in order):
    1. GILJO_ENV environment variable (dev/development)
    2. ENVIRONMENT environment variable (dev/development)
    3. Default to production (fail-safe)

    Returns:
        True if development mode, False for production
    """
    env = os.getenv("GILJO_ENV", "").lower()
    if env in ("dev", "development"):
        return True

    env = os.getenv("ENVIRONMENT", "").lower()
    # Return the condition directly
    return env in ("dev", "development")


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """
    Middleware to add security headers to all responses.

    Headers added:
    - Strict-Transport-Security (HSTS): Enforce HTTPS
    - Content-Security-Policy (CSP): Prevent XSS (hash-based, no unsafe-inline)
    - X-Frame-Options: Prevent clickjacking
    - X-Content-Type-Options: Prevent MIME sniffing
    - Referrer-Policy: Control referrer information
    - Permissions-Policy: Control browser features
    - X-XSS-Protection: Legacy XSS protection

    All headers follow OWASP security best practices.

    CSP Implementation (Handover 1007):
    - Uses SHA-256 hashes for inline scripts and styles
    - Production: No unsafe-inline or unsafe-eval
    - Development: Allows unsafe-eval for HMR (Hot Module Replacement)
    - Hashes are calculated from exact content in frontend/index.html
    """

    def __init__(self, app, hsts_max_age: int = 31536000):
        """
        Initialize security headers middleware.

        Args:
            app: FastAPI application instance
            hsts_max_age: HSTS max-age in seconds (default: 1 year)
        """
        super().__init__(app)
        self.hsts_max_age = hsts_max_age
        self.is_dev = is_development_mode()

        # Read external_host and port from config for dynamic CSP connect-src
        self.external_host = None
        self.api_port = None
        self.ssl_enabled = False
        try:
            from giljo_mcp.config_manager import get_config

            config = get_config()
            self.external_host = config.get_nested("services.external_host", default=None)
            self.api_port = config.get_nested("services.api.port", default=config.server.api_port)
            self.ssl_enabled = config.get_nested("features.ssl_enabled", default=False)
        except (ImportError, AttributeError, KeyError, TypeError):
            logger.debug("Config not available for CSP — using defaults")

        mode_str = "DEVELOPMENT" if self.is_dev else "PRODUCTION"
        logger.info(f"SecurityHeadersMiddleware initialized in {mode_str} mode")
        logger.info(f"HSTS max-age: {hsts_max_age}s")

        if self.is_dev:
            logger.warning("CSP: unsafe-eval enabled for development HMR")

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        """
        Add security headers to response.

        Args:
            request: Incoming HTTP request
            call_next: Next middleware/handler in chain

        Returns:
            Response with security headers added
        """
        response = await call_next(request)

        # HSTS: Only add for HTTPS connections (meaningless for HTTP)
        if request.url.scheme == "https":
            response.headers["Strict-Transport-Security"] = f"max-age={self.hsts_max_age}; includeSubDomains; preload"

        # CSP: Hash-based policy preventing XSS
        # Production: Strict hashes only
        # Development: Hashes + unsafe-eval for Vue HMR
        # Cloudflare: static.cloudflareinsights.com hosts the auto-injected
        # Browser Insights (RUM) beacon; harmless if you're not behind CF.
        script_src = f"'self' {CSP_SCRIPT_HASH_1} {CSP_SCRIPT_HASH_2} https://static.cloudflareinsights.com"
        if self.is_dev:
            script_src += " 'unsafe-eval'"  # Vue HMR needs eval in dev

        # connect-src: 'self' already covers same-origin API/WebSocket calls
        # (the common case). ws: / wss: allow cross-scheme WebSocket to the
        # same host. Building additional explicit host:port entries from config
        # was historically used for "defense-in-depth" but actively broke
        # reverse-proxy deployments (Cloudflare Tunnel): when the config held
        # external_host=demo.giljo.ai + api_port=7272, CSP allowed
        # `http://demo.giljo.ai:7272` while the browser loaded via
        # `https://demo.giljo.ai` — rejecting the frontend's real API calls.
        # (INF-5012b close-out.)
        # cloudflareinsights.com is the beacon endpoint paired with the
        # static.cloudflareinsights.com script source above.
        connect_src = "'self' ws: wss: https://cloudflareinsights.com"

        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; "
            f"script-src {script_src}; "
            "style-src 'self' 'unsafe-inline'; "
            "img-src 'self' data: https:; "
            "font-src 'self' data:; "
            f"connect-src {connect_src}; "
            "frame-ancestors 'none'; "  # No embedding
            "base-uri 'self'; "
            "form-action 'self'"
        )

        # X-Frame-Options: Prevent clickjacking
        response.headers["X-Frame-Options"] = "DENY"

        # X-Content-Type-Options: Prevent MIME sniffing
        response.headers["X-Content-Type-Options"] = "nosniff"

        # Referrer-Policy: Limit referrer information
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"

        # Permissions-Policy: Disable unnecessary features
        response.headers["Permissions-Policy"] = (
            "geolocation=(), "
            "microphone=(), "
            "camera=(), "
            "payment=(), "
            "usb=(), "
            "magnetometer=(), "
            "gyroscope=(), "
            "accelerometer=()"
        )

        # X-XSS-Protection: Legacy XSS protection (deprecated but harmless)
        response.headers["X-XSS-Protection"] = "1; mode=block"

        # Cache-Control: prevent stale index.html from referencing rebuilt
        # asset bundles. Vite emits content-hashed filenames under /assets/*
        # (e.g. main-DxIqQVpb.js) — those are safe to cache forever. But
        # index.html points at the *current* hashes; if a browser caches an
        # old index.html after a rebuild, it requests bundles that no longer
        # exist, the SPA 404 fallback returns index.html (text/html), and the
        # browser refuses to execute HTML as a JS module. Result: blank page
        # until hard-refresh. Force revalidation of HTML, cache hashed assets.
        if "cache-control" not in (h.lower() for h in response.headers):
            path = request.url.path
            if path.startswith("/assets/"):
                response.headers["Cache-Control"] = "public, max-age=31536000, immutable"
            else:
                content_type = response.headers.get("content-type", "")
                if content_type.startswith("text/html"):
                    response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
                    response.headers["Pragma"] = "no-cache"
                    response.headers["Expires"] = "0"

        return response
