"""
Security Headers Middleware

Adds production-grade security headers to all responses.

Created in Handover 0129c - Security Hardening & OWASP Compliance
Updated in Handover 1007 - Hash-Based CSP Implementation
"""
from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware
from typing import Callable
import logging
import os

logger = logging.getLogger(__name__)

# CSP hashes for inline code blocks in frontend/index.html
# Generated by scripts/generate_csp_hashes.py
# Regenerate if inline code changes
CSP_STYLE_HASH = "'sha256-Z2X8onHhSXt6iXyzdscOiXMXGyGcAkgrpqadNkU+Q54='"  # Loading animation styles
CSP_SCRIPT_HASH_1 = "'sha256-3R3DT5L3twAelYTnwV4Yu86c2DnUUE3OT37/Q4bdfRk='"  # API URL configuration
CSP_SCRIPT_HASH_2 = "'sha256-9XkwnMC0DQdZQu3V1Q25B0kACYwZdGz6ajUA9yEYU4k='"  # Splash screen logic


def is_development_mode() -> bool:
    """
    Detect if running in development mode.

    Checks (in order):
    1. GILJO_ENV environment variable (dev/development)
    2. ENVIRONMENT environment variable (dev/development)
    3. Default to production (fail-safe)

    Returns:
        True if development mode, False for production
    """
    env = os.getenv("GILJO_ENV", "").lower()
    if env in ("dev", "development"):
        return True

    env = os.getenv("ENVIRONMENT", "").lower()
    if env in ("dev", "development"):
        return True

    # Default to production for security (fail-safe)
    return False


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """
    Middleware to add security headers to all responses.

    Headers added:
    - Strict-Transport-Security (HSTS): Enforce HTTPS
    - Content-Security-Policy (CSP): Prevent XSS (hash-based, no unsafe-inline)
    - X-Frame-Options: Prevent clickjacking
    - X-Content-Type-Options: Prevent MIME sniffing
    - Referrer-Policy: Control referrer information
    - Permissions-Policy: Control browser features
    - X-XSS-Protection: Legacy XSS protection

    All headers follow OWASP security best practices.

    CSP Implementation (Handover 1007):
    - Uses SHA-256 hashes for inline scripts and styles
    - Production: No unsafe-inline or unsafe-eval
    - Development: Allows unsafe-eval for HMR (Hot Module Replacement)
    - Hashes are calculated from exact content in frontend/index.html
    """

    def __init__(self, app, hsts_max_age: int = 31536000):
        """
        Initialize security headers middleware.

        Args:
            app: FastAPI application instance
            hsts_max_age: HSTS max-age in seconds (default: 1 year)
        """
        super().__init__(app)
        self.hsts_max_age = hsts_max_age
        self.is_dev = is_development_mode()

        mode_str = "DEVELOPMENT" if self.is_dev else "PRODUCTION"
        logger.info(f"SecurityHeadersMiddleware initialized in {mode_str} mode")
        logger.info(f"HSTS max-age: {hsts_max_age}s")

        if self.is_dev:
            logger.warning("CSP: unsafe-eval enabled for development HMR")

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        """
        Add security headers to response.

        Args:
            request: Incoming HTTP request
            call_next: Next middleware/handler in chain

        Returns:
            Response with security headers added
        """
        response = await call_next(request)

        # HSTS: Only add for HTTPS connections (meaningless for HTTP)
        if request.url.scheme == "https":
            response.headers["Strict-Transport-Security"] = (
                f"max-age={self.hsts_max_age}; includeSubDomains; preload"
            )

        # CSP: Hash-based policy preventing XSS
        # Production: Strict hashes only
        # Development: Hashes + unsafe-eval for Vue HMR
        script_src = f"'self' {CSP_SCRIPT_HASH_1} {CSP_SCRIPT_HASH_2}"
        if self.is_dev:
            script_src += " 'unsafe-eval'"  # Vue HMR needs eval in dev

        response.headers["Content-Security-Policy"] = (
            "default-src 'self'; "
            f"script-src {script_src}; "
            f"style-src 'self' {CSP_STYLE_HASH}; "
            "img-src 'self' data: https:; "
            "font-src 'self' data:; "
            "connect-src 'self' ws: wss:; "  # WebSocket connections
            "frame-ancestors 'none'; "  # No embedding
            "base-uri 'self'; "
            "form-action 'self'"
        )

        # X-Frame-Options: Prevent clickjacking
        response.headers["X-Frame-Options"] = "DENY"

        # X-Content-Type-Options: Prevent MIME sniffing
        response.headers["X-Content-Type-Options"] = "nosniff"

        # Referrer-Policy: Limit referrer information
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"

        # Permissions-Policy: Disable unnecessary features
        response.headers["Permissions-Policy"] = (
            "geolocation=(), "
            "microphone=(), "
            "camera=(), "
            "payment=(), "
            "usb=(), "
            "magnetometer=(), "
            "gyroscope=(), "
            "accelerometer=()"
        )

        # X-XSS-Protection: Legacy XSS protection (deprecated but harmless)
        response.headers["X-XSS-Protection"] = "1; mode=block"

        return response


class CORSSecurityMiddleware(BaseHTTPMiddleware):
    """
    Enhanced CORS middleware with security controls.

    Replaces default CORS middleware with stricter controls:
    - Only allows configured origins
    - Validates Origin header
    - Supports credentials
    - Restricts allowed methods and headers

    This provides tighter security than FastAPI's default CORSMiddleware.
    """

    def __init__(self, app, allowed_origins: list = None):
        """
        Initialize CORS security middleware.

        Args:
            app: FastAPI application instance
            allowed_origins: List of allowed origin URLs (default: localhost:3000)
        """
        super().__init__(app)
        self.allowed_origins = allowed_origins or ["http://localhost:3000"]
        logger.info(f"CORSSecurityMiddleware initialized with allowed origins: {self.allowed_origins}")

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        """
        Validate origin and add CORS headers.

        Args:
            request: Incoming HTTP request
            call_next: Next middleware/handler in chain

        Returns:
            Response with CORS headers (if origin allowed)
        """
        origin = request.headers.get("origin")

        # Handle preflight OPTIONS requests
        if request.method == "OPTIONS":
            if origin in self.allowed_origins:
                response = Response()
                response.headers["Access-Control-Allow-Origin"] = origin
                response.headers["Access-Control-Allow-Credentials"] = "true"
                response.headers["Access-Control-Allow-Methods"] = "GET, POST, PUT, DELETE, OPTIONS"
                response.headers["Access-Control-Allow-Headers"] = (
                    "Content-Type, X-Tenant-Key, Authorization, X-CSRF-Token"
                )
                response.headers["Access-Control-Max-Age"] = "3600"
                return response
            else:
                # Reject unknown origins
                logger.warning(f"CORS: Rejected preflight from unknown origin: {origin}")
                return Response(status_code=403, content="Origin not allowed")

        # Process normal request
        response = await call_next(request)

        # Only allow configured origins
        if origin in self.allowed_origins:
            response.headers["Access-Control-Allow-Origin"] = origin
            response.headers["Access-Control-Allow-Credentials"] = "true"
            response.headers["Access-Control-Allow-Methods"] = "GET, POST, PUT, DELETE, OPTIONS"
            response.headers["Access-Control-Allow-Headers"] = (
                "Content-Type, X-Tenant-Key, Authorization, X-CSRF-Token"
            )
        else:
            # Reject unknown origins by not setting CORS headers
            if origin:
                logger.warning(f"CORS: Rejected request from unknown origin: {origin}")

        return response
