# Copyright (c) 2024-2026 GiljoAI LLC. All rights reserved.
# Licensed under the GiljoAI Community License v1.1.
# [CE] Community Edition -- source-available, single-user use only.

"""
Python-based validation tests for install.ps1.

These tests verify structural properties of the PowerShell installer
without requiring Pester or PowerShell execution. They run as part of
the standard pytest suite.
"""

import subprocess
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
INSTALL_PS1 = REPO_ROOT / "scripts" / "install.ps1"
START_BAT = REPO_ROOT / "scripts" / "start-giljoai.bat"


class TestInstallPs1Exists:
    """Verify the installer script file exists and is non-empty."""

    def test_script_file_exists(self):
        assert INSTALL_PS1.exists(), f"Expected {INSTALL_PS1} to exist"

    def test_script_is_not_empty(self):
        content = INSTALL_PS1.read_text(encoding="utf-8")
        assert len(content) > 100, "install.ps1 appears to be empty or truncated"


class TestInstallPs1Structure:
    """Verify the script contains required structural elements."""

    @pytest.fixture(autouse=True)
    def _load_content(self):
        self.content = INSTALL_PS1.read_text(encoding="utf-8")

    def test_requires_directive(self):
        assert "#Requires -Version 5.1" in self.content

    def test_error_action_preference(self):
        assert "$ErrorActionPreference = 'Stop'" in self.content

    def test_has_install_dir_parameter(self):
        assert "[string]$InstallDir" in self.content

    def test_has_skip_prereqs_parameter(self):
        assert "[switch]$SkipPrereqs" in self.content

    def test_has_update_parameter(self):
        assert "[switch]$Update" in self.content

    def test_phase_1_prerequisites(self):
        assert "function Test-Prerequisites" in self.content

    def test_phase_2_download(self):
        assert "function Get-LatestRelease" in self.content

    def test_phase_3_environment(self):
        assert "function Initialize-Environment" in self.content

    def test_phase_4_install_py(self):
        assert "function Invoke-InstallPy" in self.content

    def test_install_py_uses_setup_only_flag(self):
        assert "--setup-only" in self.content

    def test_phase_5_shortcuts(self):
        assert "function Install-Shortcuts" in self.content

    def test_phase_6_completion(self):
        assert "function Show-Completion" in self.content

    def test_main_wrapper_function(self):
        assert "function Invoke-GiljoInstaller" in self.content

    def test_github_repo_reference(self):
        assert "giljoai/GiljoAI_MCP" in self.content

    def test_sha256_verification(self):
        assert "Get-FileHash" in self.content
        assert "SHA256" in self.content

    def test_winget_package_ids(self):
        assert "Python.Python.3.12" in self.content
        assert "OpenJS.NodeJS.LTS" in self.content
        assert "Git.Git" in self.content

    def test_no_ai_signatures(self):
        lowered = self.content.lower()
        assert "co-authored-by" not in lowered
        assert "generated by" not in lowered

    def test_no_saas_references(self):
        assert "GILJO_MODE=saas" not in self.content
        assert "saas/" not in self.content.lower()

    def test_license_header(self):
        assert "GiljoAI Community License" in self.content


class TestInstallPs1Syntax:
    """Validate PowerShell syntax if PowerShell is available."""

    @pytest.fixture(autouse=True)
    def _check_powershell(self):
        """Skip if PowerShell is not available on this system."""
        if sys.platform != "win32":
            pytest.skip("PowerShell syntax check only runs on Windows")

    def test_powershell_parses_without_errors(self):
        """Use PowerShell's parser to check for syntax errors."""
        ps_check = (
            f"$errors = $null; "
            f"[System.Management.Automation.Language.Parser]::ParseFile("
            f"'{INSTALL_PS1}', [ref]$null, [ref]$errors); "
            f"if ($errors.Count -gt 0) {{ "
            f"$errors | ForEach-Object {{ Write-Error $_.Message }}; "
            f"exit 1 }} else {{ exit 0 }}"
        )
        result = subprocess.run(
            ["powershell", "-NoProfile", "-Command", ps_check],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        assert result.returncode == 0, f"PowerShell syntax errors in install.ps1:\n{result.stderr}"


class TestStartBat:
    """Verify the start-giljoai.bat launcher script."""

    def test_bat_file_exists(self):
        assert START_BAT.exists(), f"Expected {START_BAT} to exist"

    def test_bat_contains_activate(self):
        content = START_BAT.read_text(encoding="utf-8")
        assert "activate.bat" in content

    def test_bat_contains_run_api(self):
        content = START_BAT.read_text(encoding="utf-8")
        assert "api.run_api" in content

    def test_bat_has_echo_off(self):
        content = START_BAT.read_text(encoding="utf-8")
        assert "@echo off" in content

    def test_bat_uses_cd_dp0(self):
        content = START_BAT.read_text(encoding="utf-8")
        assert 'cd /d "%~dp0"' in content
