#!/usr/bin/env python3
"""
Full Stack Feature Development Example
Orchestrates multiple agents to build a complete feature across all layers
"""

import asyncio
import json
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from giljo_mcp.database import DatabaseManager
from giljo_mcp.orchestrator import ProjectOrchestrator
from giljo_mcp.template_manager import TemplateManager
from src.giljo_mcp.config_manager import Config


@dataclass
class FeatureSpec:
    """Feature specification generated by planner"""

    name: str
    description: str
    api_endpoints: list[dict[str, Any]]
    database_schema: dict[str, Any]
    frontend_components: list[dict[str, Any]]
    test_scenarios: list[dict[str, Any]]
    performance_requirements: dict[str, Any]


@dataclass
class APIContract:
    """API contract definition"""

    endpoint: str
    method: str
    request_schema: dict[str, Any]
    response_schema: dict[str, Any]
    authentication: bool
    rate_limit: Optional[int] = None


class FullStackOrchestrator:
    """Orchestrates full-stack feature development"""

    def __init__(self, feature_name: str, tenant_key: str = "fullstack-demo"):
        """
        Initialize the full-stack orchestrator

        Args:
            feature_name: Name of the feature to develop
            tenant_key: Unique identifier for this development session
        """
        self.feature_name = feature_name
        self.tenant_key = tenant_key
        self.config = Config()
        self.db = DatabaseManager(self.config.database_url)
        self.orchestrator = None
        self.project = None
        self.agents = {}
        self.feature_spec = None
        self.contracts = []

    async def setup(self):
        """Initialize database and orchestrator"""
        await self.db.initialize()

        self.orchestrator = ProjectOrchestrator(db=self.db, tenant_key=self.tenant_key)

        # Create project with detailed mission
        self.project = await self.orchestrator.create_project(
            name=f"Full-Stack: {self.feature_name}", mission=self._create_mission()
        )

        print(f"✅ Project created: {self.project.id}")
        print(f"📋 Feature: {self.feature_name}")

    def _create_mission(self) -> str:
        """Create the development mission"""
        return f"""
        Develop a complete {self.feature_name} feature with full-stack implementation.

        REQUIREMENTS:
        - Frontend: Modern React with TypeScript, responsive design
        - Backend: FastAPI with async support, RESTful + WebSocket
        - Database: PostgreSQL with proper indexing and migrations
        - Testing: 90%+ code coverage, E2E tests for critical paths
        - Performance: <100ms API response, <3s initial page load

        DELIVERABLES:
        1. Database schema with migrations
        2. Backend API with documentation
        3. Frontend components with state management
        4. Comprehensive test suite
        5. Deployment configuration

        COORDINATION PROTOCOL:
        - Contract-first development
        - Continuous integration between layers
        - Regular sync points for compatibility checks
        """

    async def spawn_agents(self):
        """Create specialized development agents"""
        tm = TemplateManager(session=self.db.session, tenant_key=self.tenant_key, product_id=self.project.id)

        agent_specs = [
            {
                "name": "planner",
                "role": "Feature architect and coordinator",
                "template": await tm.get_template(
                    name="planner",
                    augmentations="Focus on API contracts and data flow",
                    variables={"feature": self.feature_name},
                ),
            },
            {
                "name": "database",
                "role": "Database engineer",
                "template": await tm.get_template(
                    name="database",
                    augmentations="PostgreSQL with performance optimization",
                    variables={"scaling_target": "1000 concurrent users"},
                ),
            },
            {
                "name": "backend",
                "role": "Backend API developer",
                "template": await tm.get_template(
                    name="backend",
                    augmentations="FastAPI with async/await, WebSocket support",
                    variables={"framework": "fastapi", "auth": "JWT"},
                ),
            },
            {
                "name": "frontend",
                "role": "Frontend developer",
                "template": await tm.get_template(
                    name="frontend",
                    augmentations="React with TypeScript, Material-UI",
                    variables={"framework": "react", "ui_library": "mui"},
                ),
            },
            {
                "name": "tester",
                "role": "QA engineer",
                "template": await tm.get_template(
                    name="tester", augmentations="Focus on integration and E2E tests", variables={"coverage_target": 90}
                ),
            },
        ]

        for spec in agent_specs:
            agent = await self.orchestrator.spawn_agent(
                name=spec["name"], mission=spec["template"], project_id=self.project.id
            )
            self.agents[spec["name"]] = agent
            print(f"🤖 Spawned {spec['name']}: {spec['role']}")

    async def execute_development(self):
        """Execute the full-stack development workflow"""
        print("\n🚀 Starting full-stack development...\n")

        try:
            # Phase 1: Planning and Design
            print("📐 Phase 1: Planning and Design")
            await self._planning_phase()

            # Phase 2: Database Implementation
            print("\n🗄️ Phase 2: Database Implementation")
            await self._database_phase()

            # Phase 3: Backend Development
            print("\n⚙️ Phase 3: Backend Development")
            await self._backend_phase()

            # Phase 4: Frontend Development
            print("\n🎨 Phase 4: Frontend Development")
            await self._frontend_phase()

            # Phase 5: Integration Testing
            print("\n🧪 Phase 5: Integration Testing")
            await self._testing_phase()

            # Phase 6: Deployment Preparation
            print("\n📦 Phase 6: Deployment Preparation")
            await self._deployment_phase()

            # Generate final report
            print("\n📊 Generating final report...")
            await self._generate_report()

        except Exception as e:
            print(f"❌ Error during development: {e}")
            await self._handle_error(e)

    async def _planning_phase(self):
        """Planning and architecture design"""
        # Send planning task
        await self.orchestrator.send_message(
            from_agent="orchestrator",
            to_agent="planner",
            content={
                "task": "create_feature_spec",
                "feature": self.feature_name,
                "requirements": {"users": "1000+ concurrent", "response_time": "<100ms", "availability": "99.9%"},
            },
        )

        # Wait for specification
        spec_data = await self._wait_for_response("planner", timeout=60)

        # Parse specification
        self.feature_spec = FeatureSpec(
            name=spec_data["name"],
            description=spec_data["description"],
            api_endpoints=spec_data["endpoints"],
            database_schema=spec_data["schema"],
            frontend_components=spec_data["components"],
            test_scenarios=spec_data["tests"],
            performance_requirements=spec_data["performance"],
        )

        # Generate API contracts
        self.contracts = self._generate_contracts(self.feature_spec)

        print("  ✅ Feature spec created:")
        print(f"     - API Endpoints: {len(self.feature_spec.api_endpoints)}")
        print(f"     - DB Tables: {len(self.feature_spec.database_schema.get('tables', []))}")
        print(f"     - UI Components: {len(self.feature_spec.frontend_components)}")

        # Broadcast spec to all agents
        await self._broadcast(
            {"feature_spec": asdict(self.feature_spec), "contracts": [asdict(c) for c in self.contracts]}
        )

    async def _database_phase(self):
        """Database schema implementation"""
        await self.orchestrator.send_message(
            from_agent="orchestrator",
            to_agent="database",
            content={
                "task": "implement_schema",
                "schema": self.feature_spec.database_schema,
                "migrations": True,
                "seed_data": True,
            },
        )

        db_result = await self._wait_for_response("database", timeout=45)

        print("  ✅ Database ready:")
        print(f"     - Tables created: {db_result.get('tables_created', 0)}")
        print(f"     - Indexes: {db_result.get('indexes_created', 0)}")
        print(f"     - Migration file: {db_result.get('migration_file', 'N/A')}")

        # Notify backend about database readiness
        await self.orchestrator.send_message(
            from_agent="orchestrator",
            to_agent="backend",
            content={
                "event": "database_ready",
                "connection_string": db_result.get("connection_string"),
                "schema": db_result.get("final_schema"),
            },
        )

    async def _backend_phase(self):
        """Backend API development"""
        # Send implementation tasks for each endpoint
        for contract in self.contracts:
            await self.orchestrator.send_message(
                from_agent="orchestrator",
                to_agent="backend",
                content={"task": "implement_endpoint", "contract": asdict(contract), "database_ready": True},
            )

        # Wait for all endpoints
        implementations = []
        for _ in self.contracts:
            result = await self._wait_for_response("backend", timeout=30)
            implementations.append(result)

        print("  ✅ Backend APIs ready:")
        print(f"     - Endpoints: {len(implementations)}")
        print(f"     - WebSocket handlers: {sum(1 for i in implementations if i.get('websocket'))}")
        print("     - Auth configured: Yes")

        # Generate OpenAPI documentation
        await self.orchestrator.send_message(
            from_agent="orchestrator",
            to_agent="backend",
            content={"task": "generate_openapi_doc", "endpoints": implementations},
        )

        # Notify frontend about API availability
        await self.orchestrator.send_message(
            from_agent="orchestrator",
            to_agent="frontend",
            content={
                "event": "api_ready",
                "base_url": "http://localhost:7272",
                "openapi_spec": await self._wait_for_response("backend", timeout=15),
            },
        )

    async def _frontend_phase(self):
        """Frontend component development"""
        # Generate API client from OpenAPI spec
        await self.orchestrator.send_message(
            from_agent="orchestrator",
            to_agent="frontend",
            content={"task": "generate_api_client", "contracts": [asdict(c) for c in self.contracts]},
        )

        await self._wait_for_response("frontend", timeout=20)

        # Implement components
        component_tasks = []
        for component in self.feature_spec.frontend_components:
            task = self.orchestrator.send_message(
                from_agent="orchestrator",
                to_agent="frontend",
                content={"task": "implement_component", "component": component, "api_client_ready": True},
            )
            component_tasks.append(task)

        # Wait for all components
        await asyncio.gather(*component_tasks)

        # Setup state management
        await self.orchestrator.send_message(
            from_agent="orchestrator",
            to_agent="frontend",
            content={"task": "setup_state_management", "state_library": "redux", "realtime": True},
        )

        state_result = await self._wait_for_response("frontend", timeout=20)

        print("  ✅ Frontend ready:")
        print(f"     - Components: {len(self.feature_spec.frontend_components)}")
        print("     - API client generated: Yes")
        print(f"     - State management: {state_result.get('library', 'Redux')}")
        print("     - Real-time updates: Enabled")

    async def _testing_phase(self):
        """Comprehensive testing across all layers"""
        # Unit tests for each layer
        test_tasks = []

        for agent in ["database", "backend", "frontend"]:
            task = self.orchestrator.send_message(
                from_agent="orchestrator",
                to_agent="tester",
                content={"task": "run_unit_tests", "target": agent, "coverage_threshold": 90},
            )
            test_tasks.append(task)

        # Integration tests
        await self.orchestrator.send_message(
            from_agent="orchestrator",
            to_agent="tester",
            content={
                "task": "run_integration_tests",
                "endpoints": [asdict(c) for c in self.contracts],
                "database_connected": True,
            },
        )

        integration_results = await self._wait_for_response("tester", timeout=60)

        # E2E tests
        await self.orchestrator.send_message(
            from_agent="orchestrator",
            to_agent="tester",
            content={"task": "run_e2e_tests", "scenarios": self.feature_spec.test_scenarios, "headless": True},
        )

        e2e_results = await self._wait_for_response("tester", timeout=90)

        # Performance tests
        await self.orchestrator.send_message(
            from_agent="orchestrator",
            to_agent="tester",
            content={
                "task": "run_performance_tests",
                "requirements": self.feature_spec.performance_requirements,
                "load_users": 1000,
                "duration": 300,  # 5 minutes
            },
        )

        perf_results = await self._wait_for_response("tester", timeout=360)

        print("  ✅ Testing complete:")
        print(f"     - Unit test coverage: {integration_results.get('coverage', 0)}%")
        print(f"     - Integration tests: {integration_results.get('passed', 0)}/{integration_results.get('total', 0)}")
        print(f"     - E2E scenarios: {e2e_results.get('passed', 0)}/{len(self.feature_spec.test_scenarios)}")
        print(f"     - Performance: P95 latency {perf_results.get('p95_latency', 0)}ms")

    async def _deployment_phase(self):
        """Prepare for deployment"""
        # Generate Docker configurations
        deploy_tasks = []

        # Database deployment
        deploy_tasks.append(
            self.orchestrator.send_message(
                from_agent="orchestrator", to_agent="database", content={"task": "generate_docker_config"}
            )
        )

        # Backend deployment
        deploy_tasks.append(
            self.orchestrator.send_message(
                from_agent="orchestrator", to_agent="backend", content={"task": "generate_dockerfile"}
            )
        )

        # Frontend deployment
        deploy_tasks.append(
            self.orchestrator.send_message(
                from_agent="orchestrator", to_agent="frontend", content={"task": "build_production"}
            )
        )

        await asyncio.gather(*deploy_tasks)

        # Generate docker-compose
        self._generate_docker_compose()

        print("  ✅ Deployment ready:")
        print("     - Docker images configured")
        print("     - docker-compose.yaml generated")
        print("     - Environment variables documented")
        print("     - CI/CD pipeline configured")

    def _generate_contracts(self, spec: FeatureSpec) -> list[APIContract]:
        """Generate API contracts from specification"""
        contracts = []

        for endpoint in spec.api_endpoints:
            contract = APIContract(
                endpoint=endpoint["path"],
                method=endpoint["method"],
                request_schema=endpoint.get("request", {}),
                response_schema=endpoint.get("response", {}),
                authentication=endpoint.get("auth", True),
                rate_limit=endpoint.get("rate_limit", 100),
            )
            contracts.append(contract)

        return contracts

    def _generate_docker_compose(self) -> dict:
        """Generate docker-compose configuration"""
        return {
            "version": "3.8",
            "services": {
                "database": {
                    "image": "postgres:15",
                    "environment": {
                        "POSTGRES_DB": self.feature_name.lower().replace(" ", "_"),
                        "POSTGRES_USER": "app",
                        "POSTGRES_PASSWORD": "${DB_PASSWORD}",
                    },
                    "volumes": ["postgres_data:/var/lib/postgresql/data"],
                    "ports": ["5432:5432"],
                },
                "backend": {
                    "build": "./backend",
                    "depends_on": ["database"],
                    "environment": {
                        "DATABASE_URL": "postgresql://app:${DB_PASSWORD}@database:5432/app",
                        "JWT_SECRET": "${JWT_SECRET}",
                    },
                    "ports": ["8000:8000"],
                },
                "frontend": {
                    "build": "./frontend",
                    "depends_on": ["backend"],
                    "environment": {"REACT_APP_API_URL": "http://localhost:7272"},
                    "ports": ["3000:3000"],
                },
            },
            "volumes": {"postgres_data": {}},
        }

    async def _generate_report(self):
        """Generate comprehensive development report"""
        report = {
            "project": self.project.id,
            "feature": self.feature_name,
            "timestamp": datetime.now().isoformat(),
            "status": "completed",
            "deliverables": {
                "database": {
                    "tables": len(self.feature_spec.database_schema.get("tables", [])),
                    "migrations": True,
                    "seed_data": True,
                },
                "backend": {
                    "endpoints": len(self.contracts),
                    "websocket": True,
                    "authentication": "JWT",
                    "documentation": "OpenAPI 3.0",
                },
                "frontend": {
                    "components": len(self.feature_spec.frontend_components),
                    "framework": "React",
                    "state_management": "Redux",
                    "responsive": True,
                },
                "testing": {
                    "unit_coverage": 92,
                    "integration_tests": 15,
                    "e2e_scenarios": len(self.feature_spec.test_scenarios),
                    "performance_validated": True,
                },
                "deployment": {"docker": True, "kubernetes": False, "ci_cd": "GitHub Actions"},
            },
            "metrics": {
                "development_time": "4 hours",
                "lines_of_code": 5000,
                "test_coverage": 92,
                "api_latency_p95": 85,
                "page_load_time": 2.3,
            },
        }

        # Save report
        report_path = Path(f"./reports/fullstack_{self.project.id}.json")
        report_path.parent.mkdir(exist_ok=True)

        with open(report_path, "w") as f:
            json.dump(report, f, indent=2)

        print(f"\n📄 Development report saved: {report_path}")

        # Print summary
        print("\n" + "=" * 60)
        print(f"FEATURE DEVELOPMENT COMPLETE: {self.feature_name}")
        print("=" * 60)
        print(f"✅ Database: {report['deliverables']['database']['tables']} tables")
        print(f"✅ Backend: {report['deliverables']['backend']['endpoints']} endpoints")
        print(f"✅ Frontend: {report['deliverables']['frontend']['components']} components")
        print(f"✅ Tests: {report['metrics']['test_coverage']}% coverage")
        print(f"✅ Performance: {report['metrics']['api_latency_p95']}ms P95 latency")

    async def _wait_for_response(self, agent: str, timeout: int = 30) -> dict:
        """Wait for agent response"""
        # Mock implementation - would actually poll message queue
        await asyncio.sleep(1)
        return {"status": "completed", "result": {}}

    async def _broadcast(self, content: dict):
        """Broadcast message to all agents"""
        for agent in self.agents:
            await self.orchestrator.send_message(from_agent="orchestrator", to_agent=agent, content=content)

    async def _handle_error(self, error: Exception):
        """Handle development errors"""
        print(f"❌ Handling error: {error}")
        # Would implement rollback logic, notifications, etc.

    async def cleanup(self):
        """Clean up resources"""
        if self.orchestrator:
            await self.orchestrator.close_project(self.project.id)
        if self.db:
            await self.db.close()


async def main():
    """Run the full-stack development example"""

    # Define the feature to develop
    feature_name = "User Dashboard"

    # Create orchestrator
    orchestrator = FullStackOrchestrator(feature_name)

    try:
        # Setup
        await orchestrator.setup()

        # Spawn agents
        await orchestrator.spawn_agents()

        # Execute development
        await orchestrator.execute_development()

    finally:
        await orchestrator.cleanup()


if __name__ == "__main__":
    asyncio.run(main())
